<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$media_url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$baseurl = $objectManager->get('\Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl();

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
     <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
						 <?php  $producthint = $block->escapeHtml($_product->getProductHint());
						 	if($producthint){ ?>
								<div class="skintypelist">
								<?php
                                echo $producthint;
                                ?>
								</div>
								<?php } ?>
						 <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php $shortdefianl =  $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
									echo $shortdefianl;
									?>
                                </div>
                          <?php endif; ?>
					
						<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
					   <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>
						
                    <?php $ingredients =  $_product->getResource()->getAttribute('ingredients')->getFrontend()->getValue($_product); ?>
						<div class="ingredientspelist">
                   <?php if($ingredients){ ?>
					
						<strong><?= /* @escapeNotVerified */ __('Active Ingredients') ?></strong>
							<ul class="ingredientspelist_content">
								<?php $ingredients_array = explode(", ",$ingredients);
								 $limit=1;
								 $number =  count($ingredients_array);
								 //echo $number;
								 $i = 1;
								foreach($ingredients_array as $ingredientname){
								  if($limit<=4){
									$ingredients_collection = $objectManager->get('Emizentech\ShopByBrand\Model\Items')->getCollection()->addFieldToFilter('name', $ingredientname);
										foreach($ingredients_collection as $fillter_ingredients)
										{
											if($fillter_ingredients->getLogo() != ''){
												echo '<li class="ingredients_list"><a id = "'.$fillter_ingredients->getId().'" href="#" class="ingredients_click"><div class="ingredients_contents"><span class="ingredientimage label"><img src="'.$media_url.$fillter_ingredients->getLogo().'"/></span><span class="ingredientname label">'.$ingredientname.'<span></div></a></li>';
											}else{
												echo '<li class="ingredients_list"><a href="#" id = "'.$fillter_ingredients->getId().'" class="ingredients_click"><div class="ingredients_contents"><span class="ingredientname label noimage_ingredients">'.$ingredientname.'<span></div></a></li>';		
											}
										}
										
									} $limit++;
									
								};
								if($number == 1){
									echo '<li class="ingredients_list blank" ></li>';
									echo '<li class="ingredients_list blank" ></li>';
									echo '<li class="ingredients_list blank" ></li>';
								}elseif($number == 2){
									echo '<li class="ingredients_list blank" ></li>';
									echo '<li class="ingredients_list blank" ></li>';
								}elseif($number == 3){
									echo '<li class="ingredients_list blank" ></li>';
								}
								?>
							</ul>
						
					<?php } ?>
                            </div>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Quick Shop')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Quick Shop') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                             
                            </div>
                           
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
	<div class="popup_main_content" style="display:none;">
		<i class="fa fa-close ingredients_close"></i>
		<div class="popup_content">
		</div>
	</div>
      
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
	require([
		'jquery'
	], function( $ ) {
		$(document).ready(function() {
			$('.ingredients_click').click( function(e){
				e.preventDefault();
				var id = $(this).attr('id');
				$('.popup_content').html();
				$('body').addClass("popup_custom_overflow");
				var url = "<?php echo $baseurl.'ingredients/index/popup'; ?>";
				$.ajax({
					type: "POST",
					url: url,
					datatype: "json",
					data: {'id':id},
					showLoader: true,
					success: function(response)
					{
						showLoader: false;
						var json = $.parseJSON(response);
						if(json.status === 'success'){
							var scroll = $(window).scrollTop();
							
							$('.popup_main_content').show();
							//$('.popup_main_content').css('top',scroll+'px');
							
							$('.popup_content').html(json.html);
						}
					}
				});
			});
			
			$('.ingredients_close').click( function(e){
				$('.popup_main_content').hide();
				$('.popup_content').html();
				$('body').removeClass("popup_custom_overflow");
			});
		});

	}); 
</script>