<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Rewards
 */
?>
<?php
/**
 * @var $block \Amasty\Rewards\Block\Adminhtml\Edit\Tab\View\PersonalInfo
 */
$statistic = $block->getStatistic();
?>

<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Reward Points') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?php echo $block->getChildHtml(); ?>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Current Balance:') ?></th>
            <td><?php /* @escapeNotVerified */ echo ($statistic['positiveTotal'] + $statistic['negativeTotal']) ?> </td>
        </tr>

        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Total Earned:') ?></th>
            <td><?php /* @escapeNotVerified */ echo (int)$statistic['positiveTotal'] ?></td>
        </tr>

        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Total Spent:') ?></th>
            <td><?php /* @escapeNotVerified */ echo abs($statistic['negativeTotal']) ?></td>
        </tr>
        </tbody>
    </table>
</div>
<button data-ui-id="widget-button-1"
        onclick="jQuery('#add-points').modal('openModal')"
        class="action-default scalable"
        type="button"
        title="Add\Deduct Points"
        id="add_points_button">
    <span>Add\Deduct Points</span>
</button>