<?php
/**
 * Copyright (c) MageWorkshop. All rights reserved.
 * This source file is subject to the MageWorkshop License https://mageworkshop.com/terms-of-service
 * Do not change this file if you want to upgrade the module to the newer versions in the future
 * Please, contact us at https://mageworkshop.com/contact if you wish to customize this module according to you business needs
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var \MageWorkshop\DetailedReview\Block\Review\Product\View\Rating\AverageRating $block */
?>
<?php $averageRatings = $block->getAverageRating(); ?>
<div class="review-average-rating">
    <div class="rating-block-content">
        <?php foreach ($averageRatings as $key => $value): ?>
            <div class="rating-row">
                <div class="rating-title">
                    <span class="title"><?= $block->escapeHtml(__($key)) ?></span>
                    <span class="average"><?= $block->escapeHtml(__($value['value'])) ?></span>
                </div>
                <div class="rating-summary">
                    <div class="rating-result" title="<?= $block->escapeHtml(__($value['percent'])) ?>">
                    <span style="width:<?= $block->escapeHtml(__($value['percent'])) ?>%">
                        <span><span itemprop="ratingValue"><?= $block->escapeHtml(__($value['percent'])) ?></span>% of <span itemprop="bestRating">100</span></span>
                    </span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
