<?php
/**
 * Copyright (c) MageWorkshop. All rights reserved.
 * This source file is subject to the MageWorkshop License https://mageworkshop.com/terms-of-service
 * Do not change this file if you want to upgrade the module to the newer versions in the future
 * Please, contact us at https://mageworkshop.com/contact if you wish to customize this module according to you business needs
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var \MageWorkshop\DetailedReview\Block\Review\Product\View\Rating\ReviewRating $block */
?>
<div class="review-average-info"
     data-mage-init='{"mageWorkshop_detailedReview_reviewRating": {}}'
>
    <div class="rating-block-content">
        <div class="reviews-average-rating"><?= $block->escapeHtml(__($block->getAverageRating())) ?></div>
        <p class="reviews-average-rating-label"><?= $block->escapeHtml(__('Average rating')) ?></p>
    </div>
    <?= /* @escapeNotVerified */ $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>
</div>
