<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var \Magento\LayeredNavigation\Block\Navigation\FilterRenderer $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\LayeredNavigation\ViewModel\Layer\Filter $viewModel */
$viewModel = $block->getData('product_layer_view_model');
?>

<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
                <a
                    href="<?= $escaper->escapeUrl($filterItem->getUrl()) ?>"
                    rel="nofollow"
                ><?= /* @noEscape */ $filterItem->getLabel() ?></a>
        </li>
    <?php endforeach ?>
</ol>
