<?php
/**
 * @var \XP\OrderPdf\Block\Config $block
 */
?>
<?php
$data = $this->getShippingData();
$isHeading = $this->getIsHeading();
if ($data["shipping_description"] || $data["payment_method_info"]):
?>
<table style="<?= $data['tbl'] ?>">
    <?php if($isHeading): ?>
    <tr style="<?= $data['tr'] ?>">
        <?php if ($data["shipping_description"]): ?>
        <td style="<?= $data['td'] ?>"><h2><?= __("Shipping Method") ?></h2></td>
        <?php endif; ?>
        <?php if ($data["payment_method_info"]): ?>
        <td style="<?= $data['td'] ?>"><h2><?= __("Payment Method") ?></h2></td>
        <?php endif; ?>
    </tr>
    <?php else: ?>
    <tr style="<?= $data['tr_content'] ?>">
        <?php if ($data["shipping_description"]): ?>
        <td style="<?= $data['td_content'] ?>"><?= $data["shipping_description"] ?></td>
        <?php endif; ?>
        <?php if ($data["payment_method_info"]): ?>
        <td style="<?= $data['td_content'] ?>"><?= $data["payment_method_info"] ?></td>
        <?php endif; ?>
    </tr>
    <?php endif; ?>
</table>
<?php
endif;
