<?php
/**
 * Copyright (c) MageWorkshop. All rights reserved.
 * This source file is subject to the MageWorkshop License https://mageworkshop.com/terms-of-service
 * Do not change this file if you want to upgrade the module to the newer versions in the future
 * Please, contact us at https://mageworkshop.com/contact if you wish to customize this module according to you business needs
 */
?>
<?php // Leave message gene for the case when there are no reviews ?>
<p class="banned-customer-message"><?= $block->escapeHtml(__('Sorry, but you are not allowed to post reviews')) ?></p>
<script type="text/x-magento-init">
    {
        "*": {
            "mageWorkshop_customerPermissions_banned": {
                "message": "<?= $block->escapeHtml(__('Sorry, but you are not allowed to post reviews')) ?>"
            }
        }
    }
</script>