<?php
/**
 * Copyright (c) MageWorkshop. All rights reserved.
 * This source file is subject to the MageWorkshop License https://mageworkshop.com/terms-of-service
 * Do not change this file if you want to upgrade the module to the newer versions in the future
 * Please, contact us at https://mageworkshop.com/contact if you wish to customize this module according to you business needs
 */

/** @var MageWorkshop\CustomerPermissions\Block\Check\Rules $block */
$layout = $block->getLayout();
$name = $block->getNameInLayout();
$childBlocks = $layout->getChildNames($name);

foreach ($childBlocks as $childBlock) {
    if ($html = $block->getChildHtml($childBlock)) {
        echo $html;
        break;
    }
}


