<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Cart
 */
?>
<?php
/** @var \Amasty\Cart\Block\Config  $this */

$hlr = $this->getHelper();
//Visual Options
$backgroundColor        = $hlr->getBackgroundColor();
$headerBackgroundColor  = $hlr->getHeaderBackgroundColor();
$textColor              = $hlr->getTextColor();
$buttonTextColor        = $hlr->getButtonTextColor();
$leftButtonColor        = $hlr->getLeftButtonColor();
$rightButtonColor       = $hlr->getRightButtonColor();
?>

<style>
    #confirmButtons button span {
        color: <?= $buttonTextColor ?>;
    }

    #confirmButtons,
    #messageBox p {
        color: <?= $textColor ?>;
    }

    div#confirmBox {
        background-color: <?= $backgroundColor ?>;
    }

    #confirmButtons button.am-btn-left {
        background-color: <?= $leftButtonColor ?>;
    }

    #messageBox > .border {
        background-color: <?= $leftButtonColor ?>;
    }

    .added-item,
    .added-item:hover,
    #confirmButtons > a,
    #confirmButtons > a:hover,
    #messageBox > a:visited {
        color: <?= $headerBackgroundColor ?>;
    }

    #confirmButtons button.am-btn-right {
        background-color: <?= $rightButtonColor ?>;
    }
</style>
