<?php
/** @var $block \Rivage\SecurityLogger\Block\Adminhtml\Log\View */
?>
<h2>Admin Actions Log</h2>
<pre style="background:#222; color:#eee; padding:1em; height:300px; overflow:auto;"><?= $block->escapeHtml($block->getLogContents('admin_actions.log')) ?></pre>
<h2>Suspicious Requests Log</h2>
<pre style="background:#222; color:#eee; padding:1em; height:300px; overflow:auto;"><?= $block->escapeHtml($block->getLogContents('suspicious_requests.log')) ?></pre>
