<?php
/**
 * Copyright (c) MageWorkshop. All rights reserved.
 * This source file is subject to the MageWorkshop License https://mageworkshop.com/terms-of-service
 * Do not change this file if you want to upgrade the module to the newer versions in the future
 * Please, contact us at https://mageworkshop.com/contact if you wish to customize this module according to you business needs
 */

use MageWorkshop\Core\Helper\View;

// @codingStandardsIgnoreFile

?>
<?php /** @var \MageWorkshop\DetailedReview\Block\Review\Product\View\ListView $block */ ?>
<?php
$_items     = $block->getReviewsCollection()->getItems();
$attributes = $block->getReviewFormAttributes();
$format     = $block->getDateFormat() ? $block->getDateFormat() : \IntlDateFormatter::LONG;
/** @var MageWorkshop\Core\Helper\View $viewHelper */
$viewHelper = $block->getViewHelper();
?>
<?php if (count($_items)):?>
    <div class="block review-list" id="customer-reviews"
         data-mage-init='{"mageWorkshop_detailedReview_listReviews": {}}'
    >
        <!--    <div class="block-title">-->
        <!--        <strong>--><?php ///* @escapeNotVerified */ echo __('Customer Reviews') ?><!--</strong>-->
        <!--    </div>-->
        <hr>
        <div class="block-content">
            <div class="toolbar review-toolbar">
                <?php echo $block->getChildHtml('toolbar') ?>
            </div>
            <ol class="items review-items">

                <?php foreach ($_items as $_review): /** @var \Magento\Review\Model\Review $_review */ ?>
                    <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                        <div class="review-details">
                            <p class="review-author">
                                <strong class="review-details-value" itemprop="author"><?= $block->escapeHtml($_review->getNickname()) ?></strong>
                            </p>
                            <br>
                            <ul class="items">
                                <?php /** @var \MageWorkshop\DetailedReview\Model\Attribute $attribute */
                                foreach ($attributes as $attribute):
                                    ?>
                                    <?php if ($attribute->getIsUserDefined() &&
                                    ($value = $block->getAttributeValue($attribute, $_review))
                                    && $attribute->getAttributePlacement() === 1
                                    && !in_array($attribute->getFrontendInput(), ['textarea', 'image'])
                                ): ?>
                                    <li class="<?= $block->escapeHtml($this->getLabelClass($attribute)) ?>">
                                        <label><?= $block->escapeHtml($attribute->getFrontendLabel()) ?>:&nbsp;</label>
                                        <span>
                                        <?php if (is_array($value)): // visual swatch ?>
                                            <?php if (isset($value['src'])): ?>
                                                <br>
                                                <img src="<?= $block->escapeUrl($value['src']) ?>"
                                                     alt="<?= $block->escapeHtml($value['label']) ?>"
                                                />
                                            <?php else: // select/boolean ?>
                                                <?= $block->escapeHtml($value['label']) ?>
                                            <?php endif; ?>
                                        <?php else: // multiselect or text attributes ?>
                                            <?= $block->escapeHtml($value) ?>
                                        <?php endif; ?>
                                    </span><br>
                                    </li>
                                <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <div class="review-content" itemprop="description">
                            <div class="review-title-block">
                                <p class="review-title"><?= $block->escapeHtml($_review->getTitle()) ?></p>
                                <span><?= $block->escapeHtml(__('By')) ?></span>
                                <p class="review-author">
                                    <strong class="review-details-value" itemprop="author"><?= $block->escapeHtml($_review->getNickname()) ?></strong>
                                </p>
                                <p class="review-date">
                                    <span class="review-details-label"><?= $block->escapeHtml(__('Posted on')) ?></span>
                                    <span ><?= $block->escapeHtml(__('on')) ?></span>
                                    <time class="review-details-value" itemprop="datePublished" datetime="<?= $block->formatDate($_review->getCreatedAt(), $format) ?>">
                                        <?= $block->escapeHtml(__($block->formatDate($_review->getCreatedAt(), $format))) ?>
                                        <?= $block->escapeHtml(__($block->formatTime($_review->getCreatedAt()))) ?>
                                    </time>
                                    <!--                        <time class="review-details-value" itemprop="datePublished" datetime="--><?php ///* @escapeNotVerified */ echo $_review->getCreatedAt() ?><!--">--><?php ///* @escapeNotVerified */ echo $_review->getCreatedAt() ?><!--</time>-->
                                </p>
                            </div>
                            <?php if ($_review->getCustomerId()): ?>
                                <div id="verified-buyer" title="<?= $block->escapeHtml(__('Verified buyer')) ?>"></div>
                            <?php endif; ?>
                            <hr>
                            <p><?= /* @escapeNotVerified */ $block->addReadMore($_review->getDetail()) // escaping is done inside the method 'addReadMore()' ?></p>
                            <div class="additional-review-attributes">
                                <ul class="items">
                                    <?php foreach ($attributes as $attribute): ?>
                                        <?php if ($attribute->getFrontendInput() === 'image'): continue ?>
                                        <?php endif; ?>
                                        <?php if ($attribute->getIsUserDefined() &&
                                            ($value = $block->getAttributeValue($attribute, $_review))
                                            && (!$attribute->getAttributePlacement() || $attribute->getFrontendInput() === 'textarea')
                                        ): ?>
                                            <li class="table-items <?= $block->escapeHtml(__($this->getLabelClass($attribute))) ?>">
                                                <label><?= $block->escapeHtml(__($attribute->getFrontendLabel())) ?>:&nbsp;</label>
                                                <div class="attribute-value">
                                                    <?php if (is_array($value)): // visual swatch ?>
                                                        <?php if (isset($value['src'])): ?>
                                                            <img src="<?= $block->escapeUrl($value['src']) ?>"
                                                                 alt="<?= $block->escapeHtml(__($value['label'])) ?>"
                                                            />
                                                        <?php else: // select/boolean ?>
                                                            <?= $block->escapeHtml(__($value['label'])) ?>
                                                        <?php endif; ?>
                                                    <?php else: // multiselect or text attributes ?>
                                                        <?php if ($attribute->getFrontendInput() === 'textarea') : ?>
                                                            <?= /* @escapeNotVerified */ $value; // escaping is done inside the method 'addReadMore()' ?>
                                                        <?php else : ?>
                                                            <?= $block->escapeHtml($value); ?>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            </li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <?= $viewHelper->getListTextChildrenHtml($block, 'reviews.list.item.after', [
                                'reviews_collection' => $block->getReviewsCollection(),
                                'review' => $_review,
                                'attributes' => $attributes
                            ]);
                            ?>
                        </div>
                        <div class="review-ratings">
                            <?php if (count($_review->getRatingVotes())): // leave the container so it takes the free space ?>
                                <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                    <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                        <span class="label rating-label"><span><?= $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
                                        <div class="rating-result" title="<?= $block->escapeHtml(__($_vote->getPercent()))  ?>%">
                                            <meta itemprop="worstRating" content = "1"/>
                                            <meta itemprop="bestRating" content = "100"/>
                                            <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                        <span itemprop="ratingValue"><?= $block->escapeHtml(__($_vote->getPercent())) ?>%</span>
                                    </span>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <div class="toolbar review-toolbar">
                <?= $block->getChildHtml('toolbar') ?>
            </div>
        </div>
    </div>
<?php endif; ?>
