<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');

?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
				<div class="carthint"><?php echo $product->getProductHint(); ?></div>
				<?php //echo "<pre>"; print_r($product->getdata()); ?>
                  <?php if ($messages = $block->getMessages()){ ?>
				<div class="cartprice"></div>
				<?php } else { ?>
				<div class="cartprice"><?= $block->getUnitPriceHtml($_item) ?></div>
				     <?php } ?>
				  <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div>
						<? /*= $block->escapeHtml($message['text']) */ ?><?= __('Free') ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
				
                            
            </div>
        </td>

     
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <label class="label" for="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty">
                    <span><?= /* @escapeNotVerified */ __('Qty') ?></span>
                </label>
				<div class="field qty">
				<?php $qty = 10; ?>
                    <?php if($messages = $block->getMessages()): ?>
                        <select id="cart-<?php /* @escapeNotVerified */
                        echo $_item->getId() ?>-qty" name="cart[<?php /* @escapeNotVerified */
                        echo $_item->getId() ?>][qty]" title="<?php echo $block->escapeHtml(__('Qty')); ?>" data - cart - item -
                                id="<?php /* @escapeNotVerified */
                                echo $_item->getSku() ?>" disabled="true">
                            <?php for ($i = 1; $i <= $qty; $i++): ?>
                                <option value="<?php echo $i; ?>"<?php if ($i == $block->getQty()) {
                                    echo 'selected';
                                } ?>><?php echo $i; ?></option>
                            <?php endfor; ?>
                        </select>
                    <?php else: ?>
					<select id="cart-<?php /* @escapeNotVerified */
					echo $_item->getId() ?>-qty" name="cart[<?php /* @escapeNotVerified */
					echo $_item->getId() ?>][qty]" title="<?php echo $block->escapeHtml(__('Qty')); ?>" data - cart - item -
					id="<?php /* @escapeNotVerified */
					echo $_item->getSku() ?>">
					<?php for ($i = 1; $i <= $qty; $i++): ?>
					<option value="<?php echo $i; ?>"<?php if ($i == $block->getQty()) {
					echo 'selected';
					} ?>><?php echo $i; ?></option>
					<?php endfor; ?>
					</select>
                    <?php endif; ?>
				</div>
            </div>
			 
            <div class="actions-toolbar">
                <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
            </div>
        
        </td>

         <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
			<?php // add via dotsquares ?>
			   <?php if ($messages = $block->getMessages()){ ?>
				<div class="freemessagecart"><?= __('Free') ?></div>
				<?php } else { ?>
				 <?= $block->getRowTotalHtml($_item) ?>
			    <?php } ?>
			  <?php // add via dotsquares ?>  
			  
            <?php endif; ?>
        </td>
    </tr>
   
</tbody>
<script>
		 require([
			"jquery"
		], function($){
		//<![CDATA[
			$(document).ready(function() {
			  $('.field.qty select').change(function(){
				$(".update").trigger("click");
				//alert('hello');
					
					});
			});
		//]]>
		}); 
		//$('.field.qty select')
</script>