<?php /** * Copyright (c) MageWorkshop. All rights reserved. * This source file is subject to the MageWorkshop License https://mageworkshop.com/terms-of-service * Do not change this file if you want to upgrade the module to the newer versions in the future * Please, contact us at https://mageworkshop.com/contact if you wish to customize this module according to you business needs */ /** @var \MageWorkshop\ImageLoader\Block\Review\ImageUploader $block */ ?> <script type="text/x-magento-init">
{
    "#review-form": {
        "mageWorkshop_imageLoader_reviewFormImageValidation": {
            "maxSize": "<?= /* @escapeNotVerified */ $block->getImageLoaderHelper()->getImageSize(); ?>",
            "extensions": <?= /* @escapeNotVerified */ json_encode($block->getImageLoaderHelper()->getImageTypes()); ?>
        }
    }
}</script>