<?php
/**
 * Copyright © Rivage(info@rivage.com) All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
    /** @var Rivage\GtmExtension\Block\Datalayer $block */
    $gtmCodeSnippetViewModel = $block->getViewModel();
    $isenable = $gtmCodeSnippetViewModel->isModuleEnabled();
    $codesnippet = $gtmCodeSnippetViewModel->getGtmJsCode();
?>
<?php if ($isenable) { ?>
    <?= /* @noEscape */ $codesnippet; ?>
<?php } ?>


