<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block-discount1" id="block-discount1">
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading"
            aria-level="2"><?= /* @escapeNotVerified */ __('Promotion Code') ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
            action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/couponPost') ?>" method="post"
            data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset coupon<?= strlen($block->getCouponCode()) ? ' applied' : '' ?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="field">
                    <label for="coupon_code"
                        class="label"><span><?php echo __('Please enter promotion code if available') ?></span></label>
                    <div class="coupon-cont">
                        <div class="control">
                            <input type="text" class="input-text" id="coupon_code" name="coupon_code"
                                value="<?= $block->escapeHtml($block->getCouponCode()) ?>"
                                placeholder="<?= $block->escapeHtml(__('Enter code')) ?>" />
                        </div>

                        <div class="actions-toolbar">
                            <?php if (!strlen($block->getCouponCode())): ?>
                            <div class="primary">
                                <button class="action apply primary" type="button"
                                    value="<?= /* @escapeNotVerified */ __('Apply') ?>">
                                    <span><?= /* @escapeNotVerified */ __('Apply') ?></span>
                                </button>
                            </div>
                            <?php else: ?>
                            <div class="primary">
                                <button type="button" class="action cancel primary"
                                    value="<?= /* @escapeNotVerified */ __('Cancel') ?>"><span><?= /* @escapeNotVerified */ __('Cancel') ?></span></button>
                            </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>