<?php
/**
 * Copyright (c) MageWorkshop. All rights reserved.
 * This source file is subject to the MageWorkshop License https://mageworkshop.com/terms-of-service
 * Do not change this file if you want to upgrade the module to the newer versions in the future
 * Please, contact us at https://mageworkshop.com/contact if you wish to customize this module according to you business needs
 */

/** @var \MageWorkshop\DetailedReview\Block\Adminhtml\Review\AdditionalFieldsJs $this */
?>
<script type="text/x-magento-init">
    {
        "#select_stores": {
            "mageWorkshop_detailedReview_reviewAdditionalFields": {
                "url": "<?php /* @escapeNotVerified */ echo $this->getAjaxUrl(); ?>",
                "productId": "<?php /* @escapeNotVerified */ echo $this->getProductId(); ?>"
            }
        },

        "#edit_form": {
            "mageWorkshop_detailedReview_newReviewRatingValidation": {}
        }
    }
</script>