<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Affiliate for Magento 2
 */
/**
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<div class="block block-collapsible-nav amasty-affiliate-collapsible">
    <div class="title block-collapsible-nav-title"
         data-mage-init='{"toggleAdvanced": {"toggleContainers": "#amasty-affiliate-collapsible", "selectorsToggleClass": "active"}}'>
        <strong><?= $escaper->escapeHtml(__('Affiliate Account')) ?></strong>
    </div>
    <div class="content block-collapsible-nav-content" id="amasty-affiliate-collapsible">
        <?= $block->getChildHtml(); ?>
    </div>
</div>
