<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . __('* Required Fields') . '"';
}
?>
<div class="product-options-wrapper" id="product-options-wrapper"<?= /* @escapeNotVerified */ $required ?>>
    <div class="fieldset" tabindex="0">
        <?php
            foreach ($block->getChildNames() as $childName) {
                if ($childName !== 'html_calendar') {
                    echo $block->getChildHtml($childName);
                }
            }
        ?>
    </div>
</div>
