<div class="block-title">
   <strong><?=$block->escapeHtml(__('Our Story'))?></strong>
</div>
<!-- first slider-->
<div class="container">
   <div class="roundimage owl-carousel owl-banner1">
      <div class="item">
         <a href="#our1"><img src="<?php echo $this->getViewFileUrl('images/Rivage-Story.png'); ?>" /></a>
         <h4>قصة ريفاج</h4>
      </div>
      <div class="item">
         <a href="#our2"><img src="<?php echo $this->getViewFileUrl('images/the-blend.png'); ?>" /></a>
         <h4>تركيبة ريفاج</h4>
      </div>
      <div class="item">
         <a href="#our3"><img src="<?php echo $this->getViewFileUrl('images/be-natural.png'); ?>" /></a>
         <h4>كوني أنتِ.<br/>كوني طبيعية</h4>
      </div>
      <div class="item">
         <a href="#our4"><img src="<?php echo $this->getViewFileUrl('images/dead-sea.png'); ?>" /></a>
         <h4>البحر الميت</h4>
      </div>
      <div class="item">
         <a href="#our5"><img src="<?php echo $this->getViewFileUrl('images/miraculous.png'); ?>" /></a>
         <h4>البحر الميت - المعجزة</h4>
      </div>
      <div class="item">
         <a href="#our6"><img src="<?php echo $this->getViewFileUrl('images/research_devlop.png'); ?>" /></a>
         <h4>قسم البحث والتطوير</h4>
      </div>
      <div class="item">
         <a href="#our7"><img src="<?php echo $this->getViewFileUrl('images/natureandscience.png'); ?>" /></a>
         <h4>الطبيعة والعلوم</h4>
      </div>
      <div class="item">
         <a href="#our8"><img src="<?php echo $this->getViewFileUrl('images/the-minerals.png'); ?>" /></a>
         <h4>معادن البحر الميت</h4>
      </div>
      <div class="item">
         <a href="#our9"><img src="<?php echo $this->getViewFileUrl('images/key-minerals.png'); ?>" /></a>
         <h4>معادن البحر الميت</h4>
      </div>
      <div class="item">
         <a href="#our10"><img src="<?php echo $this->getViewFileUrl('images/key-ingradiants.png'); ?>" /></a>
         <h4>المواد الفعالة</h4>
      </div>
   </div>
</div>
<!-- second slider-->
<div class="rivagestorybanner" id="our1">
   <img src="<?php echo $this->getViewFileUrl('images/rivagestorybanner.jpg'); ?>" />
   <div class="slider-one">
      <div class="owl-banner2 owl-carousel">
         <div class="slider-content">
            <h3>نبذة عن ريفاج</h3>
            <p>بشرتك وشعرك يستحقان منك كل العناية والتغذية ليحافظا على رونقهما، ولهذا فإننا نبذل قصارى جهدنا لنضع بين يديك مزيجاً من أفضل المستخلصات النباتية الطبيعية ومعادن البحر الميت الفعالة.</p>
            <h3>تاريخ ريفاج</h3>
            <p>بدأت "ريفاج" أعمالها عام 1996، مستوحيةً منتجاتها للعناية بصحة البشرة والشعر من مزايا البحر الميت، فهذا المنتجع الطبي الطبيعي الذي اشتهر بخصائصه العلاجية منذ 3000 عام قبل الميلاد يعدّ البداية الطبية الطبيعية للعناية بالبشرة. ومن هنا جاءت منتجاتنا لتمزج ما بين الماضي والحاضر، فالمعادن والمستخلصات النباتية الغنية التي تعزز من تركيبة منتجاتنا للعناية بالبشرة قديمةٌ قِدَم التاريخ، ولكننا قمنا بدراستها وتطويرها داخل مختبراتنا، من أجل أن تحظَيْ بفائدة وتجربة لا مثيل لها في بيتك.
               إنّ كلّ منتج نقدمه لك قد تمّ تصميمه بعناية فائقة.
            </p>
            <p>ليتناغم مع المزايا الطبيعية لبشرتك، فيجدّد خلاياها ويغذّيها وينقيّها بشكل طبيعي ومن وحي الطبيعة.</p>
         </div>
         <div class="slider-content">
            <h3>رؤية ريفاج</h3>
            <p>يتم ابتكار جميع منتجات "ريفاج" بما يتماشى مع رؤيتنا.</p>
            <ul>
               <li>اختيار أفضل المواد من الطبيعة واستخدام التقنيات العلمية المتطورة لتعزيز فوائد معادن البحر الميت من خلال مزجها مع المستخلصات النباتية.</li>
               <li>الحفاظ على الصحة والجمال الطبيعي لدى المرأة والرجل وتعزيزهما بطريقة طبيعية</li>
               <li>التطوير الدائم لمنتجات عالية الجودة وحلول علاجية طبيعية للبشرة ذات أداء فائق</li>
               <li>تطوير منتجات العناية بالبشرة والشعر لتتلاءم مع
                  جميع الظروف ولتناسب مختلف الاحتياجات
               </li>
               <li>الاهتمام بجانب المسؤولية المجتمعية من خلال
                  تطوير "ريفاج" لتصبح شركة صديقة للبيئة وللمجتمع الذي تعمل فيه.
               </li>
            </ul>
         </div>
         <div class="slider-content">
            <h3>مهمة ريفاج</h3>
            <p>تكمن مهمتنا في "ريفاج" في مساعدتك على إبراز جمالك الداخلي من خلال توفير منتجات فائقة الجودة. </p>
            <p>للعناية بالبشرة والشعر. ولأنه لا يوجد في العالم غير بحر ميت واحد، أخذنا على عاتقنا مهمة تسخير. </p>
            <p>الفائدة من هذا المصدر الطبيعي الفريد وإتاحة فوائده الدفينة للجميع. وفي ذات الوقت فإن مدى إخلاصنا للجمال ولكل ما هو طبيعي واهتمامنا بتوفير منتجات عالية الأداء، يوازيه حجم التزامنا بتطوير الحلول العلاجية القديمة وبحماية بيئة البحر الميت الغنية.</p>
         </div>
      </div>
   </div>
</div>
<!-- second slider end-->
<div class="thirdslider the-bland" id="our2">
   <div class="roundimage owl-carousel owl-banner3">
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider-2-img.jpg'); ?>" />
         <div class="text-overlay">
            <h3>تركيبة ريفاج</h3>
            <p>البحر الميت الذي نستمد منه الأملاح المعدنية الطبيعية، هو عبارة عن بحيرة ملحية قديمة ويعد أكبر المنتجعات الصحية الطبيعية في العالم، حيث توفر البيئة الفريدة المحيطة به مزيجاً غنياً من المعادن الطبيعية التي تنقّي البشرة وتغذيها وتحفزها على التجدد الدائم.</p>
            <p>وما نقوم به في "ريفاج" هو مزج معادن وطين البحر الميت مع المستخلصات النباتية التي نحصل عليها من مختلف المصادر حول العالم، وهذا المزيج الحيوي هو ما يمنح منتجاتنا الفعالية والفائدة المذهلة.</p>
         </div>
      </div>
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider-2-img2.jpg'); ?>" />
         <div class="text-overlay">
            <h3>كو: ديرمال</h3>
            <p>الجلد هو حاجز طبيعي فعال جداً، ولهذا فإننا في "ريفاج" نستخدم تقنية Co:dermal™ التي تمكننا من إيصال المعادن الطبيعية والمستخلصات النباتية عبر هذا الحاجز، إلى حيث تكمن حاجتك إليها. ويشير اسم هذه التقنية إلى جمعها ما بين المكونات الفعالة حتى تعمل بالتناغم مع بعضها البعض وتؤدي إلى نتائج ملموسة. حيث تقوم تقنية.	</p>
            <p>Co:dermal بفتح المسامات وتنشيط البشرة، مما يسمح للمعادن والمستخلصات النباتية بتنظيف البشرة وتغذيتها وتجديدها من الداخل.</p>
         </div>
      </div>
   </div>
</div>
<div class="be-naturals" id="our3">
   <img src="<?php echo $this->getViewFileUrl('images/big-logo.jpg'); ?>" />
   <h4 id="be-you">كوني أنتِ. كوني طبيعية</h4>
   <h4>كوني أنتِ.</h4>
   <p>لا شكّ أن جسمك وجمالك هما من أعز ممتلكاتك، ونحن نؤمن في "ريفاج" بأن العناية بالبشرة تتعلق أساساً بتعزيز ودعم جمالك الطبيعي وصحتك، من أجل أن تتمكني من إظهار جمالك الداخلي. لذا فإن كل منتج من منتجات "ريفاج" مصمم بعناية لتغذية روحك وجمالك في آن معاً، لكي تشعري بالقوة والثقة والجاذبية في كل يوم.</p>
   <h4 id="be-natural">كوني طبيعية.</h4>
   <p>تقدّم لنا الطبيعة كمية وافرة من العناصر التي ترطب البشرة وتنعشها وتبثّ فيها الحيوية، ونحن في "ريفاج" نجمع أهمّ هذه المعادن الفعالة والمستخلصات النباتية التي تقدمها لنا الطبيعة، ليتسنى لك التمتّع بأفضل بشرة على الإطلاق.
      نشّطي وجدّدي وغذّي بشرتك مع "ريفاج" بشكل طبيعي.
   </p>
</div>
<div class="fourth-slider dead-sea" id="our4">
   <div class="roundimage owl-carousel owl-banner4">
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider2-img.jpg'); ?>" />
         <div class="text-overlay">
            <h3>البحر الميت</h3>
            <p>البحر الميت هو بحقّ أحد عجائب الدنيا الطبيعية، فبالإضافة إلى كونه من أكثر المسطحات المائية ملوحة وأكبر منتجع طبيعي في العالم، فهو يعدّ أخفض بقعة على وجه الأرض، حيث يقع على انخفاض 410 مترات تحت سطح البحر. وقد سمّي البحر الميت بهذا الاسم بسبب شدة ملوحة مياهه التي تمنع تواجد الحياة البحرية فيها.</p>
         </div>
      </div>
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider2-img2.jpg'); ?>" />
         <div class="text-overlay">
            <p>وتتميز بيئة البحر الميت النادرة من نوعها بتوفر كميات كبيرة من الطين والأملاح الغنية بالمعادن، وهو مشهور بمياهه شديدة الملوحة التي تقلل من انعكاس أشعة الشمس الضارة ، وبأجوائه ذات التركيز العالي من الأوكسجين. ومنذ آلاف السنين، يعد البحر الميت ملاذاً صحياً ومن بين أفضل الوجهات الصحية، إذ يقال أن كليوباترا كانت من أوائل النساء اللواتي عرفن الميزات المذهلة لهذا المنتجع الطبيعي، ولطالما ارتاده الزوار والسياح لاحتواء طينه ومياهه على حوالي23 نوعاً فريداً ومختلفاً من المعادن الطبيعية. </p>
            <p>واليوم أكثر من أي وقت مضى، أصبح البحر الميت يجذب الزوار من مختلف أنحاء العالم الباحثين عن العلاجات الطبيعية والاسترخاء.</p>
         </div>
      </div>
   </div>
</div>
<div class="fourth-slider the-miraculous" id="our5">
   <div class="roundimage owl-carousel owl-banner5">
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider3-img.jpg'); ?>" />
         <div class="text-overlay">
            <h3>البحر الميت - المعجزة</h3>
            <p>منذ فجر التاريخ والبحر الميت يستقطب كل من يبحث عن الاسترخاء والشفاء، فالعناصر الثلاثة الموجودة فيه من الماء والطين والأملاح المعدنية تجتمع معاً لتنعم علينا بمجموعة واسعة من الفوائد الصحية. وقد أجريت العديد من البحوث المستقلة التي أثبتت نجاح العديد من هذه الفوائد.</p>
         </div>
      </div>
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider3-img2.jpg'); ?>" />
         <div class="text-overlay">
            <p>وتحتوي أملاح البحر الميت على العديد من المعادن منها البوتاسيوم والمغنيسيوم والصوديوم والكالسيوم والبروم، وهي معادن تستعمل لعلاج الصدفية والالتهابات الجلدية والقشرة والأكزيما وحب الشباب والتهاب الجلد الزهمي. وتعمل هذه الأملاح على ترطيب البشرة وإزالة السموم منها، إلى جانب تحفيز عملية تجديد الخلايا، مما يجعلها مثالية للحد من ظهور الخطوط الرفيعة والتجاعيد.</p>
         </div>
      </div>
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider3-img3.jpg'); ?>" />
         <div class="text-overlay">
            <p>وقد تشكّل طين البحر الميت على مدى آلاف السنين بفعل اندماج عوامل أشعة الشمس والتربة والينابيع المعدنية والأنهار التي تغذي البحر الميت. ويمتص هذا الطين الغني بالعناصر المغذية كلّ الملوثات والزيوت والإفرازات من الجلد عن طريق الخاصية الأسموزية التي تقوم بسحب الشوائب خارج الجلد.</p>
         </div>
      </div>
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider3-img4.jpg'); ?>" />
         <div class="text-overlay">
            <p>وعلى الرغم من أن مياه البحر الميت المالحة غير صالحة لأن تعيش فيها كائنات حية، إلا أن البحث العلمي وجد عدة كائنات دقيقة قادرة على العيش في هذا النوع من المياه، وهي ما تُعرف باسم "دونالييلا سالينا Dunaliella salina"، وهي نوع من الطحالب الدقيقة الغنية بمادة "بيتا كاروتين beta-carotene" وتعد عنصراً فعالاً لمحاربة الشيخوخة.</p>
         </div>
      </div>
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider3-img5.jpg'); ?>" />
         <div class="text-overlay">
            <p>وعندما تجتمع أملاح البحر الميت بطينه ومياهه، فإننا نحصل على مصدر طبيعي مميز لتعزيز الجمال ومحاربة علامات تقدم السن وتغذية البشرة. ونحن في "ريفاج" نستعمل هذه العناصر لتنشيط عملية التصحيح الطبيعية وتسريع عملية تجديد خلايا البشرة، بالإضافة إلى تنظيم مستوى الرطوبة فيها وتحضيرها لاستقبال العناصر المغذية، وهذا هو أساس تقنية تركيبة "كو: ديرمال Co:dermal".</p>
         </div>
      </div>
   </div>
</div>
<div class="sixth-slider" id="our6">
   <div class="roundimage owl-carousel owl-banner6">
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider4-img.jpg'); ?>" />
         <div class="text-overlay">
            <h3>قسم البحث والتطوير</h3>
            <p>مهمتنا في "ريفاج" هي أن نستخدم الأفضل فيما تقدمه لنا الطبيعة، لنساعدك في إبراز أفضل ما لديك
               وهنا يأتي دور قسم البحث والتطوير الذي يتواصل عمله من أجل إيجاد أكثر المواد أهمية وفعاليةً ومزجها مع المكونات النشطة باستخدام طريقة.
            </p>
            <p>وهنا يأتي دور قسم البحث والتطوير الذي يتواصل عمله من أجل إيجاد أكثر المواد أهمية وفعاليةً ومزجها مع المكونات النشطة باستخدام طريقة "Co:dermal"، وهي عبارة عن تقنية ابتكرناها لتساعد في إيصال العناصر المغذية إلى حيث تحتاجها البشرة بشكل أكبر، وهذا يتضمن المزج في استخدام منتجات العناية بالبشرة من "ريفاج" حتى تصبح بشرتك مستعدة لاستقبال فوائد المكونات النشطة الطبيعية.</p>
         </div>
      </div>
      <div class="item">
         <img src="<?php echo $this->getViewFileUrl('images/slider4-img2.jpg'); ?>" />
         <div class="text-overlay">
            <h3>الجودة أولاً</h3>
            <p>نولي في "ريفاج" اهتماماً كبيراً بتقديم منتجات عالية الجودة، وهذا يدفعنا لمواصلة إيجاد أفضل المكونات والشركات المزودة عن طريق خبراء في هذا المجال. ولضمان الجودة، فإن منتجاتنا تخضع للاختبارات والتحاليل في كل مرحلة من مراحل الإنتاج، ابتداءً من مرحلة تركيب المكونات وحتى مرحلة الإنتاج النهائية، حيث يقوم بهذه الاختبارات فريق مختص وخبير بالجلد لقياس مدى فعالية هذه المنتجات. وفي ذات السياق، يتم فحص المنتجات لضمان فعاليتها وللتأكد من أنها آمنة ولا تسبب حساسية للجلد. وبطبيعة الحال، فإننا لا نقوم بتجريب منتجاتنا أبداً على الحيوانات.</p>
            <p>يدخل في تركيب منتجاتنا مكونات طبيعية ولطيفة على البشرة، ولا يتم استخدام المواد الكيميائية القوية مثل البارافين والمواد النفطية. كذلك تحمل معادن البحر الميت التي نصنّعها علامة "إيكوسيرت Ecocert" التي تضمن أنها مصنّعة بطريقة مستدامة ومسؤولة. </p>
         </div>
      </div>
   </div>
</div>
<div class="nature-and-science" id="our7">
   <img src="<?php echo $this->getViewFileUrl('images/nature-science.jpg'); ?>" />
   <div class="text-overlay">
      <h3>الطبيعة والعلوم</h3>
      <p>مهمتنا في "ريفاج" هي أن نستخدم الأفضل فيما تقدمه لنا الطبيعة، لنساعدك في إبراز أفضل ما لديك.</p>
      <h3>الطبيعة والعلم يعملان جنباً إلى جنب</h3>
      <p>تمنحنا الطبيعة المواد الخام على شكل مستخلصات نباتية ومعادن نادرة تعمل على ترطيب البشرة وتغذيتها ومعالجتها. أما العِلْم فيمدّنا بالخبرة اللازمة لتسخير القوة والفعالية التي تمتلكها المعادن والمستخلصات النباتية الموجودة في البحر الميت،.</p>
      <p>عند استعمالها كمكوّن أساسي في تركيب منتجاتنا. ومن خلال المزج ما بين الطبيعة والتقنيات العلمية، يمكننا تقديم منتجات طبيعية تمنحك نتائج مذهلة مرةً بعد مرة.</p>
   </div>
</div>
<div class="minerals" id="our8">
   <img src="<?php echo $this->getViewFileUrl('images/minrals.jpg'); ?>" />
   <div class="text-overlay">
      <h3>معادن البحر الميت</h3>
      <p>يحتوي طين البحر الميت ومياهه وأملاحه على 23 معدناً، 12 منها ليس موجوداً في أي بحر آخر في العالم
         . ومن هذه المعادن المغنيسيوم والبوتاسيوم والكلور .
      </p>
      <p>والبروم والكالسيوم والصوديوم واليود، وجميعها متحدةً تعمل على تسريع عملية الأيض في الجسم وتحافظ على توازن الماء في البشرة وتعالج الجلد من عدة أمراض، كما إنها تحفز عملية تجديد الخلايا.</p>
      <p>ومن هنا فإن طين البحر الميت من "ريفاج"، الحاصل على شهادة مجموعة "إيكو سيرت"، يمنح البشرة تركيبة فريدة من المعادن والمركبات. لذا يعدّ هذا الطين المعروف عالمياً بخصائصه العلاجية والصحية أساساً لجميع منتجاتنا.</p>
   </div>
</div>
<div class="container">
   <div class="key-minerals" id="our9">
      <h4>معادن البحر الميت</h4>
      <div class="owl-carousel keys" id="sync2">
         <div class="owl-thumb-item active-item">Li<sup>+</sup></div>
         <div class="owl-thumb-item">Na<sup>+</sup></div>
         <div class="owl-thumb-item">K<sup>+</sup></div>
         <div class="owl-thumb-item">Mg<sup>+2</sup></div>
         <div class="owl-thumb-item">Ca<sup>+2</sup></div>
         <div class="owl-thumb-item">Sr<sup>2+</sup></div>
         <div class="owl-thumb-item">Mn<sup>2+</sup></div>
         <div class="owl-thumb-item">Cu<sup>2+</sup></div>
         <div class="owl-thumb-item">Zn<sup>2+</sup></div>
         <div class="owl-thumb-item">So4<sup>-2</sup></div>
         <div class="owl-thumb-item">Br <sup>-</sup></div>
         <div class="owl-thumb-item">I <sup>-</sup></div>
      </div>
      <div class="owl-carousel mineralss" id="sync1">
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>لليثيوم</h4>
               <p>يحمي الخلايا ويحافظ على صحة الأعصاب وبالتالي يساهم في تعزيز الدورة الدموية، كما يستخدم الليثيوم في معالجة مشاكل الجلد مثل الأكزيما والصدفية.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>الصوديوم</h4>
               <p>تحتوي مياه البحر الميت على الصوديوم بنسب عالية، وهو يساعد في موازنة الرطوبة داخل البشرة كما يحسن من مرونتها ونعومتها.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>أيون البوتاسيوم</h4>
               <p>إلى جانب قدرته على تحفيز الجهاز العصبي، يعمل البوتاسيوم على موازنة مستويات زيوت البشرة، مما يساهم في الحفاظ على الرطوبة فيها والحماية من بعض مشكلات الجلد مثل حب الشباب.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>المغنيسيوم</h4>
               <p>يساعد في تسريع عملية الأيض كما يحفز عملية تحليل البروتين التي بدورها تخفف من احمرار وتهيج الجلد. ويعمل المغنيسيوم أيضاً على تهدئة الجهاز العصبي ويساعد الجلد في الحفاظ على رطوبته، كما يثبط عملية تقدم السن من خلال تعزيز عملية تجديد الخلايا بشكل طبيعي.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>الكالسيوم</h4>
               <p>يعمل على تقوية أغشية الخلايا ويعزز تجديدها، كما يعمل على تنظيف مسامات البشرة ويشكّل خطاً دفاعياً طبيعياً ضد البيئات الباردة أو الجافة أو الملوثة. كذلك يقلل الكالسيوم من الشوارد الحرة ويحسّن الدورة الدموية ويساعد في الحفاظ على رطوبة البشرة.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>السترونتيوم</h4>
               <p>يحمي أغشية الخلايا ويحافظ على مرونة الأنسجة، وبالتالي فهو يساعد في التخفيف من حدّة بعض المشكلات الجلدية مثل الصدفية والأكزيما.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>المنغنيز</h4>
               <p>يدعم عملية إنتاج الكولاجين التي بدورها تثبط من عملية تقدم السن. ويساعد المنغنيز في إنتاج الأنسجة الضامة، كما إن خصائصه المضادة للأكسدة تعمل على تغذية البشرة.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>النحاس</h4>
               <p>يعمل على تنشيط أغشية الخلايا ويحفز تكوين الإيلاستين والكولاجين في البشرة، كما يتمتع النحاس بخصائص مضادة لتصبّغ البشرة تفيد في محاربة عملية تقدم السن ومقاومة الشوارد الحرة.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>الزنك</h4>
               <p>يحفز عملية تكوين الكولاجين وتجديد الخلايا بشكل طبيعي بالإضافة إلى إصلاح الخلايا التالفة، كما يساعد الزنك في معالجة مشكلتي تساقط الشعر وحب الشباب ويحد منهما.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>الكبريتات</h4>
               <p>تحفز عملية تكوين الكولاجين الذي يحافظ على البشرة مرنة وناعمة ونضرة. ويحافظ عنصر الكبريت على صحة البشرة كونه يقضي على البكتيريا والفطريات، كما يدعم عملية تجديد الخلايا.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>البرومين</h4>
               <p>يساعد في التخفيف من شدة توتر العضلات ويحفز عملية تجديد البشرة، كما أن خصائص البرومين المضادة للالتهابات تساعد في تهدئة البشرة المتهيجة، مما يجعله علاجاً شائعاً لمشاكل الروماتيزم.</p>
            </div>
         </div>
         <div class="minerals-inner">
            <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
            <div class="minerals-content">
               <h4>اليود</h4>
               <p>ينظف البشرة ويرطبها، كما يغذي الشعر والجلد.</p>
            </div>
         </div>
      </div>
   </div>
   <div class="bottom-Key-Ingredients" id="our10">
      <h4>المواد الفعالة</h4>
      <img src="<?php echo $this->getViewFileUrl('images/bottom-indradiants.jpg'); ?>" />
      <p>المكونات الفعّالة الني نستعملها هي أساس منتجاتنا في "ريفاج"، فنحن نقوم بخلط 58 مكوناً طبيعياً بدقة وعناية مع أملاح البحر الميت وطينه لنحصل على نتائج مذهلة. وتوفر المستخلصات النباتية التي نجلبها من كافة مناطق العالم علاجات طبيعية فعالة لمشاكل الجلد الشائعة، وقد تم استعمال مستخلصات النباتات والأعشاب طبياً لقرون عدة، واليوم نقوم في "ريفاج" بدمجها مع معادن البحر الميت الفريدة.</p>
      <div class="discover-ingradiants">
         <a href="<?php echo $this->getUrl('ingredients') ?>">أكتشفي المواد الفعالة</a>
      </div>
   </div>
</div>