<?php $mediaUrl = $block->getUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$mediaUrl = str_replace('jordan/','',$mediaUrl);
?>
<div class="benefits-section section text-center aos-init aos-animate pb-0">
  <div class="custom-container">
    <h2 class="mb-5"><?php echo __('ONLINE EXCLUSIVE BENEFITS'); ?></h2>
    <div class="benefits-cont d-flex" data-aos="fade-up" data-aos-delay="300">
      <div class="benefit">
        <div class="icon">
          <img data-src="<?= /** @noEscape */ $mediaUrl . '/wysiwyg/icons/loyalty.webp' ?>" class="lazyload" alt="" />
        </div>
        <h5><?php echo __('LOYALTY REWARDS') ?></h5>
        <p><?php echo __('$1 = 1 POINTS'); ?></p>
      </div>
      <!--div class="benefit">
        <div class="icon">
          <img data-src="<?= /** @noEscape */ $mediaUrl . '/wysiwyg/icons/shipping-truck.webp' ?>" class="lazyload" alt="" />
        </div>
        <h5><?php echo __('FREE SHIPPING') ?></h5>
        <p><?php echo __('FOR ORDERS OVER $97') ?></p>
      </div-->
      <div class="benefit">
        <div class="icon">
          <img data-src="<?= /** @noEscape */ $mediaUrl . '/wysiwyg/icons/samples.webp' ?>" class="lazyload" alt="" />
        </div>
        <h5><?php echo __('3 FREE SAMPLES') ?></h5>
        <p><?php echo __('WITH ANY ORDER') ?></p>
      </div>
      <div class="benefit">
        <div class="icon">
          <img data-src="<?= /** @noEscape */ $mediaUrl . '/wysiwyg/icons/worldwide.webp' ?>" class="lazyload" alt="" />
        </div>
        <h5><?php echo __('WORLDWIDE SHIPPING') ?></h5>
        <p><?php echo __('WITHIN 3 TO 10 Days') ?></p>
      </div>
      <div class="benefit">
        <div class="icon">
          <img data-src="<?= /** @noEscape */ $mediaUrl . '/wysiwyg/icons/advice.webp' ?>" class="lazyload" alt="" />
        </div>
        <h5><?php echo __('FREE EXPERT ADVICE') ?></h5>
        <p><?php echo __('GET FREE CONSULTATION') ?></p>
      </div>
      <div class="benefit">
        <div class="icon">
          <img data-src="<?= /** @noEscape */ $mediaUrl . '/wysiwyg/cash_on_delivery.webp' ?>" class="lazyload" alt="" />
        </div>
        <h5><?php echo __('CASH ON DELIVERY') ?></h5>
        <p><?php echo __('PAY ON ARRIVAL') ?></p>
      </div>
    </div>
  </div>
</div>