<?php $mediaUrl = $block->getUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA); 
$mediaUrl = str_replace('jordan/','',$mediaUrl);
?>
<div class="mols-section section text-center pt-0 pb-5">
  <div class="custom-container">
    <div class="row">
      <div
        class="mols-box col-md-6 col-sm-12"
        data-aos="fade-up"
        data-aos-delay="300"
      >
        <img data-src="<?= /** @noEscape */ $mediaUrl . '/home/exfoliant.webp' ?>" class="lazyload" alt="" />
        <h3><?php echo __('الصابون المقشّر'); ?></h3>
        <p>
          <?php echo __('يقشّر البشرة وينظّفها ويرطبها بطريقة طبيعية.'); ?>
        </p>
        <a href="<?= /** @noEscape */ $block->getUrl('exfoliant-soap.html')?>"><?php echo __('تسوق الآن') ?></a>
      </div>
      <div
        class="mols-box col-md-6 col-sm-12"
        data-aos="fade-up"
        data-aos-delay="300"
      >
        <img data-src="<?= /** @noEscape */ $mediaUrl . '/home/toner.webp' ?>" class="lazyload" alt="" />
         <h3><?php echo __('تونر خالٍ من الكحول وغني بمعادن البحر الميت'); ?></h3>
        <p>
          <?php echo __('يغلق مسامات البشرة ويعيد إليها نضارتها وحيويتها') ?>
        </p>
        <a href="<?= /** @noEscape */ $block->getUrl('mineral-toner.html')?>"><?php echo __('تسوق الآن') ?></a>
      </div>
    </div>
  </div>
</div>