<div class="block-title">
        <strong><?= $block->escapeHtml(__('Our Story')) ?></strong>
 </div>
	<!-- first slider-->
<div class="roundimage owl-carousel owl-banner1">
   <div class="item"><img src="<?php echo $this->getViewFileUrl('images/Rivage-Story.png'); ?>" /><h4>Rivage Story</h4></div>
   <div class="item"><img src="<?php echo $this->getViewFileUrl('images/the-blend.png'); ?>" /><h4>The Bland</h4></div>
   <div class="item"><img src="<?php echo $this->getViewFileUrl('images/be-natural.png'); ?>" /><h4>Be you.<br/>Be natural</h4></div>
   <div class="item"><img src="<?php echo $this->getViewFileUrl('images/dead-sea.png'); ?>" /><h4>The Dead Sea</h4></div>
   <div class="item"><img src="<?php echo $this->getViewFileUrl('images/miraculous.png'); ?>" /><h4>The Miraculous Dea Sea</h4></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('images/Rivage-Story.png'); ?>" /><h4>Rivage Story</h4></div>
</div>

<!-- second slider-->
<div class="rivagestorybanner">
<img src="<?php echo $this->getViewFileUrl('images/rivagestorybanner.jpg'); ?>" />
<div class="slider-one">
<div class="owl-banner2 owl-carousel">
<div class="slider-content">
<h3>Rivage Story</h3>
<p>Your skin and hair deserve to be cherished, nourished and replenished. That is why we go to great lengths to source and blend nature's finest active botanicals with potent Dead Sea Minerals.</p>
<h3>Heritage</h3>
<p>Rivage began in 1996, when we were inspired by the power and results of the Dead Sea to transform the health of our skin and hair. The Dead Sea is the beginning of natural skin care - a healing and medicinal natural spa that has been celebrated since 3000 BC.  Our skincare products are a fusion of the ancient and the modern. The minerals and botanicals that enhance our skincare blends are as old as time, but they are optimized and refined by our laboratories to deliver a remarkable home spa experience.</p>
<p>Each product in our range is carefully engineered to work in harmony with your skin's natural qualities to renew, detoxify and nourish your skin, naturally.</p>
</div>
<div class="slider-content">
<h3>Vision</h3>
<p>Every Rivage product is created in accordance with our vision:</p>
<ul>
<li>To harness the best of nature, and to use science to advance the effect of Dead Sea minerals by blending them with botanical extracts.</li>
<li>To enhance and maintain beauty and well-being for men and women, naturally
</li>
<li>To consistently develop high-quality, high-performance products and treatments.
</li>
<li>To develop skin and hair care products to treat a range of conditions and suit a variety of needs.</li>
<li>To embrace social responsibility by building a business which is sustainable for the environment and our communities.</li>
</ul>
</div>
<div class="slider-content">
<h3>Mission</h3>
<p>Our mission is to help you reveal your inner beauty with natural high-performance skin and hair care products. </p>
<p>There is only one Dead Sea, and it's our mission to enhance the benefits of this outstanding natural resource and make it available to all. </p>
<p>Our devotion to beauty, nature and high performance products is matched by our dedication to enhancing ancient remedies and protecting the Dead Sea environment.</p>
</div>
</div>
</div>
</div>
<!-- second slider end-->

<div class="thirdslider">
<div class="roundimage owl-carousel owl-banner3">
   <div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider-2-img.jpg'); ?>" />
   <div class="text-overlay">
   <h3>The Blend</h3>
   <p>The Dead Sea, where our core minerals originate, is an ancient salt lake and the world's largest natural spa. The unique environment of the Dead Sea produces a rich mixture of minerals which help to clarify, stimulate, nourish and replenish your skin.</p>
   <p>We blend these minerals and Dead Sea mud with botanical extracts sourced from around the world. The fusion of minerals, mud and botanical extracts is what gives our products their astonishing potency.</p>
   </div>
   </div>
   <div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider-2-img2.jpg'); ?>" /><div class="text-overlay">
   <h3>The Blend</h3>
   <p>The Dead Sea, where our core minerals originate, is an ancient salt lake and the world's largest natural spa. The unique environment of the Dead Sea produces a rich mixture of minerals which help to clarify, stimulate, nourish and replenish your skin.</p>
   <p>We blend these minerals and Dead Sea mud with botanical extracts sourced from around the world. The fusion of minerals, mud and botanical extracts is what gives our products their astonishing potency.</p>
   </div></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider-2-img.jpg'); ?>" /><div class="text-overlay">
   <h3>The Blend</h3>
   <p>The Dead Sea, where our core minerals originate, is an ancient salt lake and the world's largest natural spa. The unique environment of the Dead Sea produces a rich mixture of minerals which help to clarify, stimulate, nourish and replenish your skin.</p>
   <p>We blend these minerals and Dead Sea mud with botanical extracts sourced from around the world. The fusion of minerals, mud and botanical extracts is what gives our products their astonishing potency.</p>
   </div></div>
   <div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider-2-img2.jpg'); ?>" /><div class="text-overlay">
   <h3>The Blend</h3>
   <p>The Dead Sea, where our core minerals originate, is an ancient salt lake and the world's largest natural spa. The unique environment of the Dead Sea produces a rich mixture of minerals which help to clarify, stimulate, nourish and replenish your skin.</p>
   <p>We blend these minerals and Dead Sea mud with botanical extracts sourced from around the world. The fusion of minerals, mud and botanical extracts is what gives our products their astonishing potency.</p>
   </div></div>
 
</div>
</div>


<div class="be-naturals">
<img src="<?php echo $this->getViewFileUrl('images/big-logo.jpg'); ?>" />
<h4>Be you. Be natural</h4>
<h4>Be you.</h4>
<p>Your body and your beauty are two of your greatest assets. We believe that skincare is about enhancing, supporting and enriching your natural beauty and well-being - helping you reveal your inner beauty. Each Rivage product is carefully formulated to nurture and replenish your natural beauty and mind, helping you to feel empowered, desirable and confident, every day.</p>
<h4>Be natural.</h4>
<p>Nature offers an abundant supply of elements which can soothe, moisturize and energize your skin. We harness nature's most powerful minerals and botanical extracts so you can experience your skin at its best. Revitalize, regenerate and replenish your skin with Rivage. Naturally.</p>
</div>



<div class="fourth-slider">
<div class="roundimage owl-carousel owl-banner4">
   <div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider2-img.jpg'); ?>" />
   <div class="text-overlay">
   <h3>The Dead Sea</h3>
  <p>The Dead Sea is a true wonder of the natural world. As well as being one of the saltiest bodies of water in the world, the Dead Sea is located at Earth’s lowest point, 410 meters below sea level. The Dead Sea is so-called because its hypersaline waters are inhospitable to marine life.</p>
   </div>
   </div>
   <div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider2-img2.jpg'); ?>" /><div class="text-overlay">
<p>In this rare environment we find mineral-rich salt and mud, hypersaline water, reduced solar radiation and a higher concentration of oxygen. For millennia the Dead Sea has attracted people looking for relaxation and optimum well-being. Cleopatra prized the formidable restorative powers of this extraordinary natural spa, while travelers have visited its shores to benefit from the rare 21 minerals that can be found in the water and mud. </p>
  <p>And today the Dead Sea is as popular as ever, drawing visitors from around the world in search of natural healing and rejuvenation.</p>
   </div></div>
 
</div>
</div>



<div class="fourth-slider">
<div class="roundimage owl-carousel owl-banner5">  
<div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider3-img.jpg'); ?>" />
<div class="text-overlay">
   <h3>The Miraculous Dead Sea</h3>
   <p>Since the dawn of civilization the Dead Sea has attracted people seeking relaxation and healing. The three key elements: mud, water and salts combine to confer a wide range of health benefits, many of which have been assessed and confirmed by independent research.</p>
   </div>
</div>
<div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider3-img2.jpg'); ?>" />
<div class="text-overlay">
<p>The salts, which include potassium, magnesium, sodium, calcium and bromides, are used to treat psoriasis, dermatitis, dandruff, eczema, acne and seborrhea. The salts moisturize, soften and detoxify while promoting cell regeneration – ideal for reducing the appearance of fine lines and wrinkles.</p>
   </div>
</div>
<div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider3-img3.jpg'); ?>" />
<div class="text-overlay">
<p>The mud is formed over thousands of years by the subtle interplay of the sun, the soil and the springs and rivers that feed into the sea. The nutrient-rich clay absorbs pollutants, fat and secretions from the skin due to an osmotic effect that draws impurities away from your skin.</p>
   </div>
</div>   
<div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider3-img4.jpg'); ?>" />
<div class="text-overlay">
<p>The water is home to few organisms because of its high salt content. One of the few organisms that can survive in the hypersaline water of the Dead Sea is Dunaliella salina, a type of micro-algae which is a rich source of beta-carotene and a powerful anti-ageing element.</p>
   </div>
</div> 
<div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider3-img5.jpg'); ?>" />
<div class="text-overlay">
<p>When the salts, the mud and the water of the Dead Sea combine you get a remarkable source of beauty-enhancing, age-delaying and skin-nourishing materials. We use these elements to activate the natural repair process, accelerate cell regeneration, regulate moisture levels, prepare the skin for nourishment. This is the essence of our Co:dermal formulation methodology.</p>
   </div>
</div> 
</div>
</div>




<div class="sixth-slider">
<div class="roundimage owl-carousel owl-banner6">  
<div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider4-img.jpg'); ?>" />
<div class="text-overlay">
   <h3>Research & Development</h3>
   <p>Our research and development work continues, as we constantly search for nature's most effective skin treatments and refine and combine active ingredients using our Co:dermal formulation methodology.</p>
   <p>Co:dermal is our technique for delivering nutrients to where your skin needs them most. This involves blending our skincare products so that the skin is prepared and activated in order to receive the benefits of our active ingredients.</p>
   </div>
</div>
<div class="item"><img src="<?php echo $this->getViewFileUrl('images/slider4-img2.jpg'); ?>" />
<div class="text-overlay">
<h3>Quality Comes First</h3>
<p>Quality is at the heart of our brand. That means we constantly strive to find the best ingredients, suppliers and industry experts. Our products are tested at every stage - from formulation to production - by a team of scientists and skin experts to measure their effectiveness. All products are tested to ensure they are effective, safe to use, and do not cause allergic reactions. And of course we never test our products on animals.</p>

<p>Our products utilize natural, skin-friendly ingredients - so we do not rely on harsh chemicals such as petroleum and paraffin. Our Dead Sea minerals carry the Ecocert mark which guarantees they are responsibly and </p>
   </div>
</div>
   
 
 
</div>
</div>




<div class="nature-and-science">  
<img src="<?php echo $this->getViewFileUrl('images/nature-science.jpg'); ?>" />
<div class="text-overlay">
   <h3>Nature & Science</h3>
   <p>Our mission is to bring out the best in nature, so we can bring out the best in you.</p>
   <h3>Nature and science, working in harmony</h3>
   <p>Nature gives us the raw materials - the exceptional botanical extracts and rare minerals that soothe, moisturize and heal your skin. Science gives us the expertise to understand the power of the Dead Sea minerals and botanical extracts at the heart of our products.</p>
   
   <p>By blending nature and science we can produce natural products that deliver remarkable results, time after time.</p>
   </div>
</div>





<div class="minerals">
<img src="<?php echo $this->getViewFileUrl('images/minrals.jpg'); ?>" />
<div class="text-overlay">
   <h3>The Minerals</h3>
   <p>The salt, mud and water of the Dead Sea contains 23 minerals, 12 of which do not exist in any other sea in the world. 
</p>
<p>These minerals include magnesium, potassium, chloride, bromide, calcium, sodium, and iodine. Together these minerals accelerate cell metabolism, regulate water balance, relieve and heal skin disorders and stimulate the natural repair process.
</p>
<p>Our Ecocert Dead Sea mud offers your skin a unique blend of minerals and compounds. This material, which is world-renowned for its healing and restorative properties, forms the basis of all of our products.</p>
   </div>
</div>
   
   
   
<div class="key-minerals">
<h4>Key Minerals</h4>
<div class="owl-carousel keys" id="sync2"> 
    <div class="owl-thumb-item">Li<sup>+</sup></div>
    <div class="owl-thumb-item">Na<sup>+</sup></div>
    <div class="owl-thumb-item">K<sup>+</sup></div>
    <div class="owl-thumb-item">Mg<sup>+2</sup></div>
     <div class="owl-thumb-item">Ca<sup>+2</sup></div>
    <div class="owl-thumb-item">Sr<sup>2+</sup></div>
    <div class="owl-thumb-item">Mn<sup>2+</sup></div>
    <div class="owl-thumb-item">Cu<sup>2+</sup></div>
     <div class="owl-thumb-item">Zn<sup>2+</sup></div>
    <div class="owl-thumb-item">So4<sup>-2</sup></div>
     <div class="owl-thumb-item">Br <sup>-</sup></div>
    <div class="owl-thumb-item">I <sup>-</sup></div>
</div>

<div class="owl-carousel mineralss" id="sync1">
    <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
        <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     
        <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     
       
        <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     <div class="minerals-inner">
    <div class="minerals-img"><img src="<?php echo $this->getViewFileUrl('images/minerals-img.jpg'); ?>" /></div>
     <div class="minerals-content"><h4>Calcium</h4><p>strengthens cell membranes and promotes skin renewal. Calcium also cleanses pores and provides a natural defense against cold, dry or polluted environments. Calcium also reduces free radicals, boosts blood circulation and helps your skin to remain moisturized.</p></div>
     </div>
     
     
   
</div>
</div>   
 
 
<div class="bottom-Key-Ingredients">
<h4>Key Ingredients</h4>
<img src="<?php echo $this->getViewFileUrl('images/bottom-indradiants.jpg'); ?>" />
<p>At the heart of Rivage products are our active ingredients. We draw from 64 natural ingredients and blend them carefully with Dead Sea salts and mud so they deliver remarkable results. The active botanical extracts that we harvest from around the world provide effective natural remedies for common skin conditions. These herbs and plant extracts have been used medicinally for centuries, and today we blend them with our unique Dead Sea minerals.</p>  
<div class="discover-ingradiants">
<a href="<?php echo $this->getUrl('ingredients')?>">Discover Our Ingredients</a>
</div>
</div>





<script type="text/javascript">
	require([
        "jquery",
        "owlcarouselslider",
    ], function ($) {
	var $= $.noConflict();
	$(document).ready(function(){
		$(".owl-banner1").owlCarousel({
			loop:true,
			margin:15,
			autoplay: false,
			responsiveClass:true,
			responsive:{
				0:{
					items:1,
					nav:true
				},
				480:{
					items:1,
					nav:true
					
				},
				767:{
					items:1,
					nav:true
					
				},
				799:{
					items:1,
					nav:true
					
				},
				1000:{
					items:5,
					nav:true,
					loop:true
				}
			}
		});
		
		// second slider
		
	$(".owl-banner2").owlCarousel({
		loop:true,
		  margin:15,
		  autoplay: false,
		  thumbs: true,
		  items:1,
		  nav:true
		});
		//third slider
	$(".owl-banner3").owlCarousel({
		  loop:true,
		  margin:15,
		  autoplay: false,
		  thumbs: true,
		  items:1,
		  nav:true
		});
		
		
			//third slider
	$(".owl-banner4").owlCarousel({
		 loop:true,
		  margin:15,
		  autoplay: false,
		  thumbs: true,
		  items:1,
		  nav:true
		});
		
		
		
		
		$(".owl-banner5").owlCarousel({
		  loop:true,
		  margin:15,
		  autoplay: false,
		  thumbs: true,
		  items:1,
		  nav:true
		});
		
		
		$(".owl-banner6").owlCarousel({
		  loop:true,
		  margin:15,
		  autoplay: false,
		  thumbs: true,
		  items:1,
		  nav:true
		});
		
		
		
		
		
		$(".owl-banner7").owlCarousel({
			loop:true,
		  margin:15,
		  autoplay: false,
		  thumbs: true,
		  items:1,
		  nav:true
		});
		
		
		
	});
}); 	
</script>


<script type="text/javascript">
	require([
        "jquery",
        "owlcarouselslidercustom",
    ], function ($) {
	var $= $.noConflict();
	$(document).ready(function(){
		var sync1 = $("#sync1");
		var sync2 = $("#sync2");

		sync1.owlCarousel({
			singleItem : true,
			slideSpeed : 2000,
			navigation: true,
			pagination:false,
			afterAction : syncPosition,
			responsiveRefreshRate : 200,
		});

		sync2.owlCarousel({
			items : 12,
			itemsDesktop  : [1199,12],
			itemsDesktopSmall : [979,10],
			itemsTablet       : [768,8],
			itemsMobile       : [479,4],
			pagination:false,
			margin:15,
			responsiveRefreshRate : 100,
			afterInit : function(el){
			  el.find(".owl-item").eq(0).addClass("active");
			}
		});

		function syncPosition(el){
			var current = this.currentItem;
			$("#sync2")
			.find(".owl-item")
			.removeClass("active")
			.eq(current)
			.addClass("active")
			if($("#sync2").data("owlCarousel") !== undefined){
				center(current)
			}
		}

		$("#sync2").on("click", ".owl-item", function(e){
			e.preventDefault();
			var number = $(this).data("owlItem");
			sync1.trigger("owl.goTo",number);
		});

		function center(number){
			var sync2visible = sync2.data("owlCarousel").owl.visibleItems;
			var num = number;
			var found = false;
			for(var i in sync2visible){
				if(num === sync2visible[i]){
					var found = true;
				}
			}

			if(found===false){
				if(num>sync2visible[sync2visible.length-1]){
					sync2.trigger("owl.goTo", num - sync2visible.length+2)
				}else{
					if(num - 1 === -1){
						num = 0;
					}
					sync2.trigger("owl.goTo", num);
				}
			}
			else if(num === sync2visible[sync2visible.length-1]){
				sync2.trigger("owl.goTo", sync2visible[1])
			} else if(num === sync2visible[0]){
				sync2.trigger("owl.goTo", num-1)
			}
		}
	});
}); 	
</script>	


