<div id="header-nav" class="navigation">
<?php
	$objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
	$customerSession = $objectManagerr->get('Magento\Customer\Model\Session');
	$helper = $objectManagerr->get('\Netbaseteam\Megamenu\Helper\Data');
	$detect = $objectManagerr->get('\Netbaseteam\Megamenu\Helper\Detect');
	$mobilestatus = $helper->getMobileEnable();
	$mobileposition = $helper->getMobilePosition();
	$deviceType = ($detect->isMobile() ? ($detect->isTablet() ? 'tablet' : 'phone') : 'computer');
	if(!$helper->getPosition()) {
		$position = 1; /* top menu for default */
	} else {
		$position = $helper->getPosition();
	}
	
if($helper->isEnable()){
	
?>
	<div id = "nb_mn_computer">
	<?php
		echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')
				->setBlockId('top.links')->toHtml(); 

	?>

	<?php
		if($position == \Netbaseteam\Megamenu\Model\Config\Source\Menutype::HORIZONTAL) {
			echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
					->setTemplate('Netbaseteam_Megamenu::topmenu.phtml')->toHtml();
		}
	?>

	<?php
		if($position == \Netbaseteam\Megamenu\Model\Config\Source\Menutype::VERTICAL) {
			echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
					->setTemplate('Netbaseteam_Megamenu::vertical.phtml')->toHtml();
		}
	?>
	
	<?php
		if($position == \Netbaseteam\Megamenu\Model\Config\Source\Menutype::BOTH) {
			echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
					->setTemplate('Netbaseteam_Megamenu::topmenu.phtml')->toHtml();
					
			echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
					->setTemplate('Netbaseteam_Megamenu::vertical.phtml')->toHtml(); 
		}
	?>
	</div>
	
	<div id = "nb_mn_mobile">

	
	<?php if ($mobilestatus == 1): ?>
		<div class="navigation_mgmn">
			<div class="mobile-menu-top">
				<a href="#" class="mobile-menu-close">
					<i class="fas fa-times"></i>
				</a>
				<?php
				echo $this->getLayout()
				->createBlock("Magento\Customer\Block\Account\AuthorizationLink")
				->setTemplate("Magento_Customer::account/link/authorization.phtml")
				->toHtml();
				?>
			</div>
			<?php if ($mobileposition == 1): ?>
				<?php echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
					->setTemplate('Netbaseteam_Megamenu::topmenu.phtml')->toHtml();?>
			<?php endif ?>
			<?php if ($mobileposition == 2): ?>
				<?php echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
					->setTemplate('Netbaseteam_Megamenu::vertical_mb.phtml')->toHtml();?>
			<?php endif ?>
			<?php if ($mobileposition == 3): ?>
				<?php echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
					->setTemplate('Netbaseteam_Megamenu::topmenu.phtml')->toHtml();?>
				<?php echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
				->setTemplate('Netbaseteam_Megamenu::vertical_mb.phtml')->toHtml();?>
			<?php endif ?>
			<style type="text/css">
				.navigation {
	   				display: none;
				}	
				.sections.nav-sections {
	   				background: white;
				}
			</style>
		</div>
	<?php endif ?>	
	</div>

<?php
	
} else { /* when disable megamenu will show default menu */
	echo $this->getLayout()->createBlock('Magento\Theme\Block\Html\Topmenu\Interceptor')
			->setTemplate('Magento_Theme::html/topmenu.phtml')->toHtml(); 
} 
?>
</div>

