<?php
	$objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
	$objBlock = $objectManagerr->get('\Netbaseteam\Megamenu\Block\Navigation');
	$productHelper = $objectManagerr->get('\Magento\Catalog\Helper\Product');
	//\zend_debug::dump($objBlock->getCollection(20)->getData());
	$c_contact = Netbaseteam\Megamenu\Model\Contenttype::Contact;/* 7 */
	$c_pgrid = Netbaseteam\Megamenu\Model\Contenttype::Product_Grid;/* 4 */
	$c_dynamic_cat = Netbaseteam\Megamenu\Model\Contenttype::Dynamic_Category_Listing;/* 2 */
	$c_plist = Netbaseteam\Megamenu\Model\Contenttype::Product_Listing;/* 5 */
	$c_static = Netbaseteam\Megamenu\Model\Contenttype::Static_Category_Listing; /* 3 */
	$c_pcat_list = Netbaseteam\Megamenu\Model\Contenttype::Product_Listing_Category; /* 6 */
	$currentStoreId = $objBlock->getCurrentStoreId();
?>

<?php /******** Root Cateogry - Level 1 ********/ ?>
<div id="nb_megamenu_ver" class="wrap-vertical-menu col-lg-3">
	<span class="btn-menu">all category</span>
	<div class="magemenu-menu vertical-menu">
		<div class="header-nav">
			<h4 class="no-display">Default Menu</h4>
			<ul class="nav-exploded explodedmenu nbtype-1">
				
				<?php
				$helper = $objectManagerr->get('\Netbaseteam\Megamenu\Helper\Data');
				$childrens = $objBlock->getSubCategories($helper->getRootCatID());
				$submenu_class = "";
				?>
				
				<?php 
				foreach ($childrens as $cat){ 
					$cat_id = $cat["entity_id"];
					$v_label = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_label, $cat_id);
					$menu_position 	=  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::position, $cat_id);
					
					$column  	=  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_num_columns, $cat_id);
					if($column == 0 || $column == "") $column = 5;
					
					$childrens2 = $objBlock->getSubCategories($cat_id);
					
					$v_icon = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_cat_icon, $cat_id);
					$top_block = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_block_top, $cat_id);
					$bottom_block 	=  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_block_bottom, $cat_id);
					$left_block = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_block_left, $cat_id);
					$left_sku = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_left_sku, $cat_id);
					$right_block = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_block_right, $cat_id);
					$right_sku = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_right_sku, $cat_id);
					$sku_pspecial 	=  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_sku, $cat_id);
					
					$parent_class 	= ""; $block_class = "";
					
					if(count($childrens2)) {
						$submenu_class = "parentMenu";
					}
					$content_type = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_content_type, $cat_id);//default
					$content_type_name = "nbtype-".$content_type;
					
					$left_sku 		=  trim($objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_left_sku, $cat_id));
					if($left_sku){
						$left_block 	= "";
						$l_data = array();
						$l_data[] = $left_sku;
						$l_data[] = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_left_sku_title, $cat_id);
					}
					
					$right_sku 		=  trim($objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_right_sku, $cat_id));
					if($right_sku){	
						$right_block 	= "";
						$r_data = array();
						$r_data[] = $right_sku;
						$r_data[] = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_right_sku_title, $cat_id);
					}
					$storeid = explode(",",$objBlock->getStoreIds($cat_id));
					?>
						<?php if ( in_array("0", $storeid) || in_array($currentStoreId, $storeid) || $menu_position == ""): ?>
							<?php if($menu_position == \Netbaseteam\Megamenu\Model\Position::left_menu 
									|| $menu_position == ""
									|| $menu_position == \Netbaseteam\Megamenu\Model\Position::both){ ?>
									
								<li class="menu <?php if(count($childrens2)){echo "parentMenu";}?> <?php echo $content_type_name; ?>">
									<!-- vertical menu -->
									
									<?php if ($objBlock->getcusLinkUrl($cat_id) == ""): ?>
										<a href="<?php echo $objBlock->_getCatUrl($cat) ?>">
									<?php else: ?>	
										<a href="<?php echo $objBlock->getcusLinkUrl($cat_id) ?>">
									<?php endif ?>
									<?php if ($objBlock->getImageUrl($cat_id) == ""): ?>

									<?php else: ?>
										<span style="float: left;"><img  style="width: 2em;" class="img.mgmn" src="<?php echo "pub\media\Megamenu\\".$objBlock->getImageUrl($cat_id);?>"></span>
									<?php endif ?>
									<?php if ($objBlock->getIconselect($cat_id) == ""): ?>

									<?php else: ?>
										<span style="float: left;font-size: 1.5em;" class="ic-category">
											<i class="<?php echo $objBlock->getIconselect($cat_id);?>"></i>
										</span>
									<?php endif ?>
									<?php if($v_label != ""){ ?>
									<img alt="" src="<?php echo $v_label;?>">
									<?php } ?>
									
									<span>
									<?php if($v_icon != ""){ ?>
										<img width="25px" src="<?php echo $helper->getBaseUrl().'/'. $v_icon; ?>" />
									<?php } ?>
									<?php if($v_icon != ""){ ?>
										<img width="25px" src="<?php echo $helper->getBaseUrl().'/'. $v_icon; ?>" />
									<?php } ?>
									<?php echo $cat->getName() ?>
									</span>
									</a>
									
									<?php if(count($childrens2) && $content_type != $c_contact && $content_type != $c_pgrid && $content_type != $c_dynamic_cat && $content_type != $c_plist && $content_type != $c_static){ ?>
									<div class="explodedmenu-menu-popup" id="popup4">
										<div class="exploded-cms-block static-block">
											<div class="inner-cms-block <?php echo $parent_class; ?> <?php echo $block_class; ?>">
												<!-- top block --> 
												<?php if($top_block){ ?>
												<div class="block block-top">
													<?php 
													echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
													->getBlockFilter()->filter($top_block);
													?>
												</div>
												<?php } ?>
												<div class="clearfix"></div>
												<!-- end static block top -->
												<!-- left block check khi nao co block thi moi show div block block-left -->  
													<?php 
													if($left_block){
													?>
													<div class="block block-left">
														<?php 
														echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
														->getBlockFilter()->filter($left_block);
														?>
													</div>
													<?php } ?>
													
													<?php 
														if($left_sku){
													?>
													<div class="block block-left">
														<?php
															echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
																	->setData('block_data', $l_data)
																	->setTemplate('Netbaseteam_Megamenu::sku.phtml')->toHtml(); 
														?>
													</div>
													<?php }  ?>
													
													<!-- end static block left -->
													<!-- sub-categories  -->
													<div class="block block-cate">
														<?php foreach ($childrens2 as $cate){ ?>
														<?php /*** level 3 ***/ ?>
														<?php $childrens3 = $objBlock->getSubCategories($cate["entity_id"]); ?>
														<div class="subcate <?php if(count($childrens3)){echo "subparent";}?>">
															<h3>
																<a href="<?php echo $objBlock->_getCatUrl($cate) ?>"><?php echo $cate["name"] ?></a>
															</h3>
															<?php if(count($childrens3)){ ?>
															<ul class="itemsubmenu">
																<?php foreach ($childrens3 as $cate){ ?>
																<?php /*** level 4 ***/ ?>
																<?php $childrens4 = $objBlock->getSubCategories($cate["entity_id"]); ?>
																<li class="itemMenu level4 <?php if(count($childrens4)){echo "subparent";}?>">
																	<a href="<?php echo $objBlock->_getCatUrl($cate) ?>"><?php echo $cate["name"] ?></a>
																	<?php if(count($childrens4)){ ?>
																	<ul class="itemsubmenu level4">
																		<?php foreach ($childrens4 as $cate){ ?>
																		<?php /*** level 5 ***/ ?>
																		<?php $childrens5 = $objBlock->getSubCategories($cate["entity_id"]); ?>
																		<li class="itemMenu level5 <?php if(count($childrens5)){echo "subparent";}?>">
																			<a href="<?php echo $objBlock->_getCatUrl($cate) ?>" class="itemMenuName level2"><span><?php echo $cate["name"] ?></span></a>
																			<?php if(count($childrens5)){ ?>
																			<ul class="itemsubmenu level5">
																				<?php foreach ($childrens5 as $cate){ ?>
																				<li class="itemMenu level6">
																					<a href="<?php echo $objBlock->_getCatUrl($cate) ?>" class="itemMenuName level6"><span><?php echo $cate["name"] ?></span></a>
																				</li>
																				<?php } ?>
																			</ul>
																			<?php } ?>
																		</li>
																		<?php } /* end level4 */ ?>
																	</ul>
																	<?php } /* end level4 */ ?>
																</li>
																<?php } /* end level3 */ ?>
															</ul>
															<?php } /* end level3 */ ?>
														</div>
														<?php } /* end level2 */ ?>
													</div>
													<!-- end sub-categories -->
													<!-- block show specical product -->

													<?php
													if($sku_pspecial){
													?>
													<div class="block block-product">
														<div class="product-grid">
															<div class="inner">
																<div class="item">
																	<?php 
																		/* block title for product */
																		$p = $objBlock->_getProductData($sku_pspecial);
																		$title_pspecial =  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_label_container, $cat_id);												
																		if($title_pspecial){
																	?>
																	<h2><?php echo $title_pspecial ?></h2>
																	<?php } ?>
																	<div class="product-info">
																		<a class="product-image" href="<?php echo $p->getProductUrl() ?>"><img src="<?php echo $objectManagerr->get('\Magento\Catalog\Helper\Image')->init($p, 'product_small_image')->resize(250, 250)->getUrl(); ?>" width="250" height="250" alt="<?php //echo $this->htmlEscape($p->getName()) ?>" />
																		</a>
																		<h2 class="product-name"><a title="<?php echo $p->getName() ?>" href="<?php echo $p->getProductUrl() ?>"><?php echo $p->getName() ?></a></h2>
																		<?php
																			$formattedPrice = $objBlock->showPrice($p->getPrice());
																		?>
																		<div class="price-box">											
																			<p class="old-price"> 
																				<span class="price">
																				<?php echo $formattedPrice ?>   
																				</span>
																			</p>

																			<button class="action tocart primary"
																					data-post='<?php echo $objBlock->_getAddToCartUrl($p); ?>'
																					type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																				<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																			</button>
																			
																		</div>
																		<div class="actions">
																			<?php 
																			if($p->getShortDescription() == ""){
																				$_mydesc = $helper->limit_text($p->getDescription(), 7);
																			} else {
																				$_mydesc = $helper->limit_text($p->getShortDescription(), 7); 
																			}
																			?>
																			<p><?php echo $_mydesc ?><a href="<?php echo $p->getProductUrl() ?>"><?php echo __('read more') ?></a></p>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
													<?php } ?>
													
													<!-- block show specical product -->
													<!-- right block anh check cho em khi nao co thi moi hien thi block -->
													<?php 
														if($right_block){
														?>
													<div class="block block-right">
														<?php 
														echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
														->getBlockFilter()->filter($right_block);
														?>
													</div>
													<?php } ?>
													
													<?php 
													if($right_sku){
													?>
													<div class="block block-right">
													
														<?php
														
														echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
																	->setData('block_data', $r_data)
																	->setTemplate('Netbaseteam_Megamenu::sku.phtml')->toHtml(); 
														?>
													</div>
													<?php } ?>
													
													<!-- end content block right --> 
												 
												<div class="clearfix"></div>
												<!-- bottom block --> 
												<?php 
													if($bottom_block){
													?>
												<div class="block block-bottom">
													<?php 
													echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
													->getBlockFilter()->filter($bottom_block);
													?>	
												</div>
												<?php } ?>
												<!-- end content block bottom -->
											</div>
										</div>
									</div>
									<?php } ?>
									<!-- end product listing by sub-categories -->
									
									<!-- contact menu -->
									<?php
									if($content_type == $c_contact) {
										$idenf =  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_content_block, $cat_id);
										if($idenf){
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block">
											<div class="inner-cms-block my-contact-form"> 
												<?php 
													echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
													->getBlockFilter()->filter($idenf);
													//echo $idenf; 
												?>					
											</div>

										</div>
									</div>
										<?php } ?>
									<?php } ?>
									
									<!-- product grid menu -->
									<?php
									if($content_type == $c_pgrid) {
										$title = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_box_title, $cat_id);
										$arr_ids = explode(",", $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_products, $cat_id));
										$n = count($arr_ids);
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block">
											<div class="inner-cms-block row-productgrid">
				                                <p><strong class="pgrid_title_menu"><?php echo $title; ?></strong> </p>
												<!-- foreach -->
												<?php for($i=0; $i < $n; $i++){ ?>
												<?php
													$pid = trim($arr_ids[$i]);
													$p = $objBlock->_loadProduct($pid); 
												?>
												<div class="col-nb-<?php echo $column; ?>">
													<a href="<?php echo $p->getProductUrl(); ?>">
													<img width="135" height="135" src="<?php echo $objectManagerr->get('\Magento\Catalog\Helper\Image')->init($p, 'product_small_image')->resize(135, 135)->getUrl(); ?>"></a>
													<a href="<?php echo $p->getProductUrl() ?>" class="mm-product-name"><strong><?php echo $p->getName(); ?></strong></a>
													<?php
														$formattedPrice = $objBlock->showPrice($p->getPrice());
													?>
													<div class="price-box">
														<p class="old-price"> 
															<span class="price">
															<?php echo $formattedPrice ?>   
															</span>
														</p>
													</div>
												</div>
												<?php } ?>
											</div>
										</div>
									</div>
									<?php } ?>
									
									<!-- dynamic icon menu -->
									<?php 
									if($content_type == $c_dynamic_cat) {
										$ver_pgrid_cats = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_cats, $cat_id)
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block">
											<div class="inner-cms-block row-cate-grid">
											<?php if($ver_pgrid_cats == ""){ ?>
												<?php foreach ($childrens2 as $cate){ ?>
													<div class="form-group text-center col-nb-<?php echo $column; ?>">
														<?php
															$cat_id = $cate["entity_id"];
															$cat_name = $cate["name"];
															$category = $objBlock->_loadCat($cat_id);
														?>
														<a href="<?php echo $objBlock->_getCatUrl($category) ?>">
														<?php if($category->getImageUrl()) { ?>
															<span class="">
															<img src="<?php echo $category->getImageUrl(); ?>">
															</span>
														<?php } ?>	
														</a>
														<a class="mm-cate-name" href="<?php echo $objBlock->_getCatUrl($category) ?>"><span class=""><?php echo $cat_name ?></span></a>
													</div>
												<?php } ?>	
											<?php 
											} else {
												$arr_cats = explode(",", $ver_pgrid_cats);
												for ($i=0; $i < count($arr_cats); $i++){ ?>
													<div class="form-group text-center col-nb-<?php echo $column; ?>">
														<?php
															$cat_id = trim($arr_cats[$i]);
															$category = $objBlock->_loadCat($cat_id);
															$cat_name = $category->getName();
														?>
														<a href="<?php echo $objBlock->_getCatUrl($category); ?>">
														<?php if($category->getImageUrl()) { ?>
															<span class="">
															<img src="<?php echo $category->getImageUrl(); ?>">
															</span>
														<?php } ?>	
														</a>
														<a class="mm-cate-name" href="<?php echo $objBlock->_getCatUrl($category); ?>"><span class=""><?php echo $cat_name ?></span></a>
													</div>
												<?php }
											} ?>
											</div>
										</div>
									</div>
									<?php } ?>
									
									<!-- product list menu -->
									<?php 
									if($content_type == $c_plist) {
										$title = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_box_title, $cat_id);
										$arr_ids = explode(",", $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_products, $cat_id));
										/* \zend_debug::dump($arr_ids); */
										$n = count($arr_ids);
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block _row-product-list">
											<!-- block 1 -->
											<div class="inner-cms-block row-product-list col-sm-9">
												<p><strong class=""><?php echo $title; ?></strong></p>
												<!-- foreach -->
												<?php for($j=0; $j < $column; $j++): ?>
												<div class="col-nb-<?php echo $column; ?>">
													<?php for($i=0; $i < $n; $i++){ ?>
													<?php
														$pid = trim($arr_ids[$i]);
														$p = $objBlock->_loadProduct($pid); 
														if(($i % $column) == $j):
													?>				
													<div class="nb_lbl_type">
														<?php if($this->_getVerLabel($cat_id, $pid, \Netbaseteam\Megamenu\Model\Label::lblNew)){ ?>
														<img src="<?php echo $this->getViewFileUrl('Netbaseteam_Megamenu/images/icon_new.png'); ?>">	
														<?php } ?>
														<?php if($this->_getVerLabel($cat_id, $pid, \Netbaseteam\Megamenu\Model\Label::lblHot)){ ?>
														<img src="<?php echo $this->getViewFileUrl('Netbaseteam_Megamenu/images/icon_hot.png'); ?>">	
														<?php } ?>
														<?php if($this->_getVerLabel($cat_id, $pid, \Netbaseteam\Megamenu\Model\Label::lblSale)){ ?>
														<img src="<?php echo $this->getViewFileUrl('Netbaseteam_Megamenu/images/icon_sale.png'); ?>">	
														<?php } ?>
														<a href="<?php echo $p->getProductUrl(); ?>" class="form-group plist-pname"><span><?php echo $p->getName(); ?></span></a>
													</div>
													<?php endif;} ?>
												</div>
												<?php endfor; ?>
											</div>
											<!-- block 2 -->
											<?php
											$idenf =  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_content_block, $cat_id);
											if($idenf){
											?>
											<div id="block-2" class="block-2 row-product-list col-sm-3">
												<?php 
												echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
												->getBlockFilter()->filter($idenf);
												?>
											</div>
											<?php } ?>
										</div>
									</div>
									<?php } ?>
									
									
									<!-- static categories menu (categories by column) -->
									<?php 
									if($content_type == $c_static) {
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block _row-static-cate-grid">
											<!-- block 1 -->
											<div class="inner-cms-block row-static-cate-grid col-sm-9">
												<!-- foreach column categories -->
												<?php $childrens = $objBlock->getSubCategories($cat_id); ?>
												<?php foreach ($childrens as $cate){ ?>
												<div class="col-category col-nb-<?php echo $column; ?>">	
													<?php 
														$sub_cat_id = $cate["entity_id"];
														$cat_name = $cate["name"];
														$category = $objBlock->_loadCat($sub_cat_id);
													?>
													<?php if($category->getImageUrl()) { ?>
														<span class="">
														<img src="<?php echo $category->getImageUrl(); ?>" class="img-responsive">
														</span>
													<?php } ?>
													
													<a href="<?php echo $objBlock->_getCatUrl($category) ?>" class="nb_pstatic_cat"><?php echo $cat_name ?></a>
													<?php $childrens2 = $objBlock->getSubCategories($sub_cat_id); ?>
													<!-- foreach items in column -->
													<?php foreach ($childrens2 as $cate){ ?>
														<a href="<?php echo $objBlock->_getCatUrl($cate) ?>" class="">+ <?php echo $cate["name"] ?></a>
													<?php } ?>
												</div>
												<?php } ?>	
											</div>
											<!-- block 2 -->
											<?php
											$idenf =  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_content_block, $cat_id);
											if($idenf){
											?>
											<div id="block-col2" class="inner-cms-block row-static-cate-grid col-sm-3">
												<?php 
												echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
												->getBlockFilter()->filter($idenf);
												?>
											</div>
											<?php } ?>	
										</div>
									</div>
									<?php } ?>
									
									
									<!-- product listing by sub-categories  -->
									<?php if($content_type == $c_pcat_list) { ?>
									<?php 
										$dynamic_cats = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_cats, $cat_id);
										if($dynamic_cats != ""){
											$arr_cats = explode(",", $dynamic_cats);
										} else {
											foreach ($childrens2 as $cate){
												$arr_cats[] = $cate["entity_id"];
											}
										}
									?>
									<?php
									if(count($arr_cats) > 1) {
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block static-block product_list_by_sub_cat">
											<div class="inner-cms-block">
												<div class="row">
													<div class="col-sm-3">
														<ul class="">
															<?php 
															for ($i=0; $i < count($arr_cats); $i++){ 
																$cat_id = trim($arr_cats[$i]);
																$category = $objBlock->_loadCat($cat_id);
																$cat_name = $category->getName();	
															?>
															<li title="Click Item To Show Product Grid" class="subcate_list <?php if($i == 0) echo ' active';?>" data-toggle="subcate-<?php echo $i; ?>"><span class=""><?php echo $cat_name ?></span></li>
															<?php } ?>
														</ul>
													</div>
												<div class="col-sm-9">
												<?php 
													for ($i=0; $i < count($arr_cats); $i++){ 
														$cat_id = trim($arr_cats[$i]);
														$category = $objBlock->_loadCat($cat_id);
														$cat_name = $category->getName();                                                                        
														$products = $category = $objBlock->_loadCat($cat_id)
																	 ->getProductCollection()
																	 ->addAttributeToSelect('entity_id') // add all attributes - optional
																	 ->addAttributeToFilter('status', 1) // enabled
																	 ->addAttributeToFilter('visibility', 4)  //visibility in catalog,search	
																	 ->setPageSize(7);	
															
													?>                                   
													<div class="subcate subcate_content <?php if($i == 0) echo ' active';?>" id="subcate-<?php echo $i; ?>">
														<!-- foreach -->
														<?php 
															$count_link = 0;
															foreach($products as $p){ 
																$count_link ++;
																$pid = $p->getId();
																$p = $objBlock->_loadProduct($pid); 
															?>
															<div class="col-nb-<?php echo $column; ?>">
																<a href="<?php echo $p->getProductUrl(); ?>" class="">
																<img width="135" height="135" src="<?php echo $objectManagerr->get('\Magento\Catalog\Helper\Image')->init($p, 'product_small_image')->resize(135, 135)->getUrl(); ?>"></a>
																<a href="<?php echo $p->getProductUrl() ?>" class="mm-product-name"><strong><?php echo $p->getName(); ?></strong></a>
																<?php
																	$formattedPrice = $objBlock->showPrice($p->getPrice());
																?>
																<div class="price-box">
																	<p class="old-price"> 
																		<span class="price">
																		<?php echo $formattedPrice ?>   
																		</span>
																	</p>
																</div>
															</div>
															
															<?php if($count_link > 5) { ?>
															<div class="pull-right"><a href="<?php echo $objBlock->_getCatUrl($cat); ?>"><?php echo __('View More'); ?></a></div>
															<?php break; ?>								
															<?php } ?>
															
														<?php } ?>
													</div>
													<?php } ?>
												</div>
				                              </div>
											</div>
										</div>
									</div>
									<?php } ?>
									<?php } ?>
									<!-- end product listing by sub-categories -->
									
									
								</li>
								
							<?php } /* end position */ ?>
						<?php endif ?>
				<?php } /* end foreach */ ?>
				<?php foreach ($objBlock->getCustomContentMenu() as $menu_items): ?>
					<?php 
						$cat_id = $menu_items;
						$v_label = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_label, $cat_id);
						$menu_position 	=  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::position, $cat_id);
						
						$column  	=  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_num_columns, $cat_id);
						if($column == 0 || $column == "") $column = 5;
						
						$childrens2 = [];
						
						$v_icon = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_cat_icon, $cat_id);
						$top_block = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_block_top, $cat_id);
						$bottom_block 	=  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_block_bottom, $cat_id);
						$left_block = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_block_left, $cat_id);
						$left_sku = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_left_sku, $cat_id);
						$right_block = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_block_right, $cat_id);
						$right_sku = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_right_sku, $cat_id);
						$sku_pspecial 	=  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_sku, $cat_id);
						
						$parent_class 	= ""; $block_class = "";
						
						if(count($childrens2)) {
							$submenu_class = "parentMenu";
						}
						$content_type = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_content_type, $cat_id);//default
						$content_type_name = "nbtype-".$content_type;
						
						$left_sku 		=  trim($objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_left_sku, $cat_id));
						if($left_sku){
							$left_block 	= "";
							$l_data = array();
							$l_data[] = $left_sku;
							$l_data[] = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_left_sku_title, $cat_id);
						}
						
						$right_sku 		=  trim($objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_right_sku, $cat_id));
						if($right_sku){	
							$right_block 	= "";
							$r_data = array();
							$r_data[] = $right_sku;
							$r_data[] = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_right_sku_title, $cat_id);
						}
						$storeid = explode(",",$objBlock->getStoreIds($cat_id));
					?>
					<?php if ( in_array("0", $storeid) || in_array($currentStoreId, $storeid) || $menu_position == ""): ?>
							<?php if($menu_position == \Netbaseteam\Megamenu\Model\Position::left_menu 
									|| $menu_position == ""
									|| $menu_position == \Netbaseteam\Megamenu\Model\Position::both){ ?>
									
								<li class="menu <?php if(count($childrens2)){echo "parentMenu";}?> <?php echo $content_type_name; ?>">
									<!-- vertical menu -->
									
									<?php if ($objBlock->getcusLinkUrl($cat_id) == ""): ?>
										<a href="#">
									<?php else: ?>	
										<a href="<?php echo $objBlock->getcusLinkUrl($cat_id) ?>">
									<?php endif ?>
									<?php if ($objBlock->getImageUrl($cat_id) == ""): ?>

									<?php else: ?>
										<span style="float: left;"><img  style="width: 2em;" class="img.mgmn" src="<?php echo "pub\media\Megamenu\\".$objBlock->getImageUrl($cat_id);?>"></span>
									<?php endif ?>
									<?php if ($objBlock->getIconselect($cat_id) == ""): ?>

									<?php else: ?>
										<span style="float: left; font-size: 1.5em;" class="ic-category">
											<i class="<?php echo $objBlock->getIconselect($cat_id);?>"></i>
										</span>
									<?php endif ?>
									<?php if($v_label != ""){ ?>
									<img alt="" src="<?php echo $v_label;?>">
									<?php } ?>
									
									<span>
									<?php if($v_icon != ""){ ?>
										<img width="25px" src="<?php echo $helper->getBaseUrl().'/'. $v_icon; ?>" />
									<?php } ?>
									<?php if($v_icon != ""){ ?>
										<img width="25px" src="<?php echo $helper->getBaseUrl().'/'. $v_icon; ?>" />
									<?php } ?>
									<?php echo $objBlock->getMenuName($cat_id); ?>
									</span>
									</a>
									
									<?php if(count($childrens2) && $content_type != $c_contact && $content_type != $c_pgrid && $content_type != $c_dynamic_cat && $content_type != $c_plist && $content_type != $c_static){ ?>
									<div class="explodedmenu-menu-popup" id="popup4">
										<div class="exploded-cms-block static-block">
											<div class="inner-cms-block <?php echo $parent_class; ?> <?php echo $block_class; ?>">
												<!-- top block --> 
												<?php if($top_block){ ?>
												<div class="block block-top">
													<?php 
													echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
													->getBlockFilter()->filter($top_block);
													?>
												</div>
												<?php } ?>
												<div class="clearfix"></div>
												<!-- end static block top -->
												<!-- left block check khi nao co block thi moi show div block block-left -->  
													<?php 
													if($left_block){
													?>
													<div class="block block-left">
														<?php 
														echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
														->getBlockFilter()->filter($left_block);
														?>
													</div>
													<?php } ?>
													
													<?php 
														if($left_sku){
													?>
													<div class="block block-left">
														<?php
															echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
																	->setData('block_data', $l_data)
																	->setTemplate('Netbaseteam_Megamenu::sku.phtml')->toHtml(); 
														?>
													</div>
													<?php }  ?>
													
													<!-- end static block left -->
													<!-- sub-categories  -->
													<div class="block block-cate">
														<?php foreach ($childrens2 as $cate){ ?>
														<?php /*** level 3 ***/ ?>
														<?php $childrens3 = $objBlock->getSubCategories($cate["entity_id"]); ?>
														<div class="subcate <?php if(count($childrens3)){echo "subparent";}?>">
															<h3>
																<a href="<?php echo $objBlock->_getCatUrl($cate) ?>"><?php echo $cate["name"] ?></a>
															</h3>
															<?php if(count($childrens3)){ ?>
															<ul class="itemsubmenu">
																<?php foreach ($childrens3 as $cate){ ?>
																<?php /*** level 4 ***/ ?>
																<?php $childrens4 = $objBlock->getSubCategories($cate["entity_id"]); ?>
																<li class="itemMenu level4 <?php if(count($childrens4)){echo "subparent";}?>">
																	<a href="<?php echo $objBlock->_getCatUrl($cate) ?>"><?php echo $cate["name"] ?></a>
																	<?php if(count($childrens4)){ ?>
																	<ul class="itemsubmenu level4">
																		<?php foreach ($childrens4 as $cate){ ?>
																		<?php /*** level 5 ***/ ?>
																		<?php $childrens5 = $objBlock->getSubCategories($cate["entity_id"]); ?>
																		<li class="itemMenu level5 <?php if(count($childrens5)){echo "subparent";}?>">
																			<a href="<?php echo $objBlock->_getCatUrl($cate) ?>" class="itemMenuName level2"><span><?php echo $cate["name"] ?></span></a>
																			<?php if(count($childrens5)){ ?>
																			<ul class="itemsubmenu level5">
																				<?php foreach ($childrens5 as $cate){ ?>
																				<li class="itemMenu level6">
																					<a href="<?php echo $objBlock->_getCatUrl($cate) ?>" class="itemMenuName level6"><span><?php echo $cate["name"] ?></span></a>
																				</li>
																				<?php } ?>
																			</ul>
																			<?php } ?>
																		</li>
																		<?php } /* end level4 */ ?>
																	</ul>
																	<?php } /* end level4 */ ?>
																</li>
																<?php } /* end level3 */ ?>
															</ul>
															<?php } /* end level3 */ ?>
														</div>
														<?php } /* end level2 */ ?>
													</div>
													<!-- end sub-categories -->
													<!-- block show specical product -->

													<?php
													if($sku_pspecial){
													?>
													<div class="block block-product">
														<div class="product-grid">
															<div class="inner">
																<div class="item">
																	<?php 
																		/* block title for product */
																		$p = $objBlock->_getProductData($sku_pspecial);
																		$title_pspecial =  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_label_container, $cat_id);												
																		if($title_pspecial){
																	?>
																	<h2><?php echo $title_pspecial ?></h2>
																	<?php } ?>
																	<div class="product-info">
																		<a class="product-image" href="<?php echo $p->getProductUrl() ?>"><img src="<?php echo $objectManagerr->get('\Magento\Catalog\Helper\Image')->init($p, 'product_small_image')->resize(250, 250)->getUrl(); ?>" width="250" height="250" alt="<?php //echo $this->htmlEscape($p->getName()) ?>" />
																		</a>
																		<h2 class="product-name"><a title="<?php echo $p->getName() ?>" href="<?php echo $p->getProductUrl() ?>"><?php echo $p->getName() ?></a></h2>
																		<?php
																			$formattedPrice = $objBlock->showPrice($p->getPrice());
																		?>
																		<div class="price-box">											
																			<p class="old-price"> 
																				<span class="price">
																				<?php echo $formattedPrice ?>   
																				</span>
																			</p>

																			<button class="action tocart primary"
																					data-post='<?php echo $objBlock->_getAddToCartUrl($p); ?>'
																					type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																				<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																			</button>
																			
																		</div>
																		<div class="actions">
																			<?php 
																			if($p->getShortDescription() == ""){
																				$_mydesc = $helper->limit_text($p->getDescription(), 7);
																			} else {
																				$_mydesc = $helper->limit_text($p->getShortDescription(), 7); 
																			}
																			?>
																			<p><?php echo $_mydesc ?><a href="<?php echo $p->getProductUrl() ?>"><?php echo __('read more') ?></a></p>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
													<?php } ?>
													
													<!-- block show specical product -->
													<!-- right block anh check cho em khi nao co thi moi hien thi block -->
													<?php 
														if($right_block){
														?>
													<div class="block block-right">
														<?php 
														echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
														->getBlockFilter()->filter($right_block);
														?>
													</div>
													<?php } ?>
													
													<?php 
													if($right_sku){
													?>
													<div class="block block-right">
													
														<?php
														
														echo $this->getLayout()->createBlock('Netbaseteam\Megamenu\Block\Navigation')
																	->setData('block_data', $r_data)
																	->setTemplate('Netbaseteam_Megamenu::sku.phtml')->toHtml(); 
														?>
													</div>
													<?php } ?>
													
													<!-- end content block right --> 
												 
												<div class="clearfix"></div>
												<!-- bottom block --> 
												<?php 
													if($bottom_block){
													?>
												<div class="block block-bottom">
													<?php 
													echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
													->getBlockFilter()->filter($bottom_block);
													?>	
												</div>
												<?php } ?>
												<!-- end content block bottom -->
											</div>
										</div>
									</div>
									<?php } ?>
									<!-- end product listing by sub-categories -->
									
									<!-- contact menu -->
									<?php
									if($content_type == $c_contact) {
										$idenf =  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_content_block, $cat_id);
										if($idenf){
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block">
											<div class="inner-cms-block my-contact-form"> 
												<?php 
													echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
													->getBlockFilter()->filter($idenf);
													//echo $idenf; 
												?>					
											</div>

										</div>
									</div>
										<?php } ?>
									<?php } ?>
									
									<!-- product grid menu -->
									<?php
									if($content_type == $c_pgrid) {
										$title = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_box_title, $cat_id);
										$arr_ids = explode(",", $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_products, $cat_id));
										$n = count($arr_ids);
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block">
											<div class="inner-cms-block row-productgrid">
				                                <p><strong class="pgrid_title_menu"><?php echo $title; ?></strong> </p>
												<!-- foreach -->
												<?php for($i=0; $i < $n; $i++){ ?>
												<?php
													$pid = trim($arr_ids[$i]);
													$p = $objBlock->_loadProduct($pid); 
												?>
												<div class="col-nb-<?php echo $column; ?>">
													<a href="<?php echo $p->getProductUrl(); ?>">
													<img width="135" height="135" src="<?php echo $objectManagerr->get('\Magento\Catalog\Helper\Image')->init($p, 'product_small_image')->resize(135, 135)->getUrl(); ?>"></a>
													<a href="<?php echo $p->getProductUrl() ?>" class="mm-product-name"><strong><?php echo $p->getName(); ?></strong></a>
													<?php
														$formattedPrice = $objBlock->showPrice($p->getPrice());
													?>
													<div class="price-box">
														<p class="old-price"> 
															<span class="price">
															<?php echo $formattedPrice ?>   
															</span>
														</p>
													</div>
												</div>
												<?php } ?>
											</div>
										</div>
									</div>
									<?php } ?>
									
									<!-- dynamic icon menu -->
									<?php 
									if($content_type == $c_dynamic_cat) {
										$ver_pgrid_cats = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_cats, $cat_id)
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block">
											<div class="inner-cms-block row-cate-grid">
											<?php if($ver_pgrid_cats == ""){ ?>
												<?php foreach ($childrens2 as $cate){ ?>
													<div class="form-group text-center col-nb-<?php echo $column; ?>">
														<?php
															$cat_id = $cate["entity_id"];
															$cat_name = $cate["name"];
															$category = $objBlock->_loadCat($cat_id);
														?>
														<a href="<?php echo $objBlock->_getCatUrl($category) ?>">
														<?php if($category->getImageUrl()) { ?>
															<span class="">
															<img src="<?php echo $category->getImageUrl(); ?>">
															</span>
														<?php } ?>	
														</a>
														<a class="mm-cate-name" href="<?php echo $objBlock->_getCatUrl($category) ?>"><span class=""><?php echo $cat_name ?></span></a>
													</div>
												<?php } ?>	
											<?php 
											} else {
												$arr_cats = explode(",", $ver_pgrid_cats);
												for ($i=0; $i < count($arr_cats); $i++){ ?>
													<div class="form-group text-center col-nb-<?php echo $column; ?>">
														<?php
															$cat_id = trim($arr_cats[$i]);
															$category = $objBlock->_loadCat($cat_id);
															$cat_name = $category->getName();
														?>
														<a href="<?php echo $objBlock->_getCatUrl($category); ?>">
														<?php if($category->getImageUrl()) { ?>
															<span class="">
															<img src="<?php echo $category->getImageUrl(); ?>">
															</span>
														<?php } ?>	
														</a>
														<a class="mm-cate-name" href="<?php echo $objBlock->_getCatUrl($category); ?>"><span class=""><?php echo $cat_name ?></span></a>
													</div>
												<?php }
											} ?>
											</div>
										</div>
									</div>
									<?php } ?>
									
									<!-- product list menu -->
									<?php 
									if($content_type == $c_plist) {
										$title = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_box_title, $cat_id);
										$arr_ids = explode(",", $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_products, $cat_id));
										/* \zend_debug::dump($arr_ids); */
										$n = count($arr_ids);
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block _row-product-list">
											<!-- block 1 -->
											<div class="inner-cms-block row-product-list col-sm-9">
												<p><strong class=""><?php echo $title; ?></strong></p>
												<!-- foreach -->
												<?php for($j=0; $j < $column; $j++): ?>
												<div class="col-nb-<?php echo $column; ?>">
													<?php for($i=0; $i < $n; $i++){ ?>
													<?php
														$pid = trim($arr_ids[$i]);
														$p = $objBlock->_loadProduct($pid); 
														if(($i % $column) == $j):
													?>				
													<div class="nb_lbl_type">
														<?php if($this->_getVerLabel($cat_id, $pid, \Netbaseteam\Megamenu\Model\Label::lblNew)){ ?>
														<img src="<?php echo $this->getViewFileUrl('Netbaseteam_Megamenu/images/icon_new.png'); ?>">	
														<?php } ?>
														<?php if($this->_getVerLabel($cat_id, $pid, \Netbaseteam\Megamenu\Model\Label::lblHot)){ ?>
														<img src="<?php echo $this->getViewFileUrl('Netbaseteam_Megamenu/images/icon_hot.png'); ?>">	
														<?php } ?>
														<?php if($this->_getVerLabel($cat_id, $pid, \Netbaseteam\Megamenu\Model\Label::lblSale)){ ?>
														<img src="<?php echo $this->getViewFileUrl('Netbaseteam_Megamenu/images/icon_sale.png'); ?>">	
														<?php } ?>
														<a href="<?php echo $p->getProductUrl(); ?>" class="form-group plist-pname"><span><?php echo $p->getName(); ?></span></a>
													</div>
													<?php endif;} ?>
												</div>
												<?php endfor; ?>
											</div>
											<!-- block 2 -->
											<?php
											$idenf =  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_content_block, $cat_id);
											if($idenf){
											?>
											<div id="block-2" class="block-2 row-product-list col-sm-3">
												<?php 
												echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
												->getBlockFilter()->filter($idenf);
												?>
											</div>
											<?php } ?>
										</div>
									</div>
									<?php } ?>
									
									
									<!-- static categories menu (categories by column) -->
									<?php 
									if($content_type == $c_static) {
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block _row-static-cate-grid">
											<!-- block 1 -->
											<div class="inner-cms-block row-static-cate-grid col-sm-9">
												<!-- foreach column categories -->
												<?php $childrens = $objBlock->getSubCategories($cat_id); ?>
												<?php foreach ($childrens as $cate){ ?>
												<div class="col-category col-nb-<?php echo $column; ?>">	
													<?php 
														$sub_cat_id = $cate["entity_id"];
														$cat_name = $cate["name"];
														$category = $objBlock->_loadCat($sub_cat_id);
													?>
													<?php if($category->getImageUrl()) { ?>
														<span class="">
														<img src="<?php echo $category->getImageUrl(); ?>" class="img-responsive">
														</span>
													<?php } ?>
													
													<a href="<?php echo $objBlock->_getCatUrl($category) ?>" class="nb_pstatic_cat"><?php echo $cat_name ?></a>
													<?php $childrens2 = $objBlock->getSubCategories($sub_cat_id); ?>
													<!-- foreach items in column -->
													<?php foreach ($childrens2 as $cate){ ?>
														<a href="<?php echo $objBlock->_getCatUrl($cate) ?>" class="">+ <?php echo $cate["name"] ?></a>
													<?php } ?>
												</div>
												<?php } ?>	
											</div>
											<!-- block 2 -->
											<?php
											$idenf =  $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_content_block, $cat_id);
											if($idenf){
											?>
											<div id="block-col2" class="inner-cms-block row-static-cate-grid col-sm-3">
												<?php 
												echo $objectManagerr->get('Magento\Cms\Model\Template\FilterProvider')
												->getBlockFilter()->filter($idenf);
												?>
											</div>
											<?php } ?>	
										</div>
									</div>
									<?php } ?>
									
									
									<!-- product listing by sub-categories  -->
									<?php if($content_type == $c_pcat_list) { ?>
									<?php 
										$dynamic_cats = $objBlock->getMenuField(Netbaseteam\Megamenu\Model\Fields::left_pgrid_cats, $cat_id);
										if($dynamic_cats != ""){
											$arr_cats = explode(",", $dynamic_cats);
										} else {
											foreach ($childrens2 as $cate){
												$arr_cats[] = $cate["entity_id"];
											}
										}
									?>
									<?php
									if(count($arr_cats) > 1) {
									?>
									<div class="explodedmenu-menu-popup">
										<div class="exploded-cms-block static-block product_list_by_sub_cat">
											<div class="inner-cms-block">
												<div class="row">
													<div class="col-sm-3">
														<ul class="">
															<?php 
															for ($i=0; $i < count($arr_cats); $i++){ 
																$cat_id = trim($arr_cats[$i]);
																$category = $objBlock->_loadCat($cat_id);
																$cat_name = $category->getName();	
															?>
															<li title="Click Item To Show Product Grid" class="subcate_list <?php if($i == 0) echo ' active';?>" data-toggle="subcate-<?php echo $i; ?>"><span class=""><?php echo $cat_name ?></span></li>
															<?php } ?>
														</ul>
													</div>
												<div class="col-sm-9">
												<?php 
													for ($i=0; $i < count($arr_cats); $i++){ 
														$cat_id = trim($arr_cats[$i]);
														$category = $objBlock->_loadCat($cat_id);
														$cat_name = $category->getName();                                                                        
														$products = $category = $objBlock->_loadCat($cat_id)
																	 ->getProductCollection()
																	 ->addAttributeToSelect('entity_id') // add all attributes - optional
																	 ->addAttributeToFilter('status', 1) // enabled
																	 ->addAttributeToFilter('visibility', 4)  //visibility in catalog,search	
																	 ->setPageSize(7);	
															
													?>                                   
													<div class="subcate subcate_content <?php if($i == 0) echo ' active';?>" id="subcate-<?php echo $i; ?>">
														<!-- foreach -->
														<?php 
															$count_link = 0;
															foreach($products as $p){ 
																$count_link ++;
																$pid = $p->getId();
																$p = $objBlock->_loadProduct($pid); 
															?>
															<div class="col-nb-<?php echo $column; ?>">
																<a href="<?php echo $p->getProductUrl(); ?>" class="">
																<img width="135" height="135" src="<?php echo $objectManagerr->get('\Magento\Catalog\Helper\Image')->init($p, 'product_small_image')->resize(135, 135)->getUrl(); ?>"></a>
																<a href="<?php echo $p->getProductUrl() ?>" class="mm-product-name"><strong><?php echo $p->getName(); ?></strong></a>
																<?php
																	$formattedPrice = $objBlock->showPrice($p->getPrice());
																?>
																<div class="price-box">
																	<p class="old-price"> 
																		<span class="price">
																		<?php echo $formattedPrice ?>   
																		</span>
																	</p>
																</div>
															</div>
															
															<?php if($count_link > 5) { ?>
															<div class="pull-right"><a href="<?php echo $objBlock->_getCatUrl($cat); ?>"><?php echo __('View More'); ?></a></div>
															<?php break; ?>								
															<?php } ?>
															
														<?php } ?>
													</div>
													<?php } ?>
												</div>
				                              </div>
											</div>
										</div>
									</div>
									<?php } ?>
									<?php } ?>
									<!-- end product listing by sub-categories -->
									
									
								</li>
								
							<?php } /* end position */ ?>
					<?php endif ?>
				<?php endforeach; ?>
			</ul>
		</div>	
	</div>
</div>

<script type="text/javascript">
	require([
		'jquery'
		], function(jQuery){
		jQuery(document).ready(function(){
			jQuery('li.subcate_list').each(function(){
				var c = jQuery(this).data('toggle');
				jQuery(this).on('click', function(){
					jQuery('li.subcate_list').removeClass('active');
					jQuery('.subcate_content').removeClass('active');
					jQuery(this).addClass('active');
					jQuery('.subcate_content#' + c).addClass('active');
				});
			});
		});
		jQuery(window).load(function(){ 
			jQuery(".vertical-menu .inner-cms-block").each(function(){
						var block_left = 0;
						var block_cate = 0;
						var block_product = 0;
						var block_right = 0;
						var inner_cms_block = 0;
						block_left = jQuery(this).find(".block-left").innerWidth();
						block_cate = jQuery(this).find(".block-cate").innerWidth();
						block_product = jQuery(this).find(".block-product").innerWidth();
						block_right = jQuery(this).find(".block-right").innerWidth();  
						inner_cms_block = block_left + block_cate + block_product + block_right; 
						if(jQuery(this).hasClass('nb-repare-width')){
							inner_cms_block += 110;
						}else{
							inner_cms_block += 30; 
						} 
						if(jQuery(this).hasClass('block-full')){
							inner_cms_block +=25;
						};
						if(!jQuery(this).hasClass('row-static-cate-grid') && !jQuery(this).hasClass('row-product-list')){
							jQuery(this).css('width',inner_cms_block); 
						} 
					});
			jQuery('.wrap-vertical-menu .btn-menu').on('click',function(){
			if(jQuery('.vertical-menu').hasClass('show')){
				jQuery(".vertical-menu").removeClass('show');
			}else{
				jQuery(".vertical-menu").addClass('show');
			} 
			jQuery(".vertical-menu li.menu").each(function(){
					var w_container = jQuery("#header-nav").width(); 
					var w_parent = jQuery(this).width(); 
					var w_child = w_container - w_parent; 
					jQuery(this).find(".explodedmenu-menu-popup .row-productgrid, .explodedmenu-menu-popup .my-contact-form, .explodedmenu-menu-popup .row-cate-grid,.explodedmenu-menu-popup ._row-product-list, .explodedmenu-menu-popup ._row-static-cate-grid, .explodedmenu-menu-popup .product_list_by_sub_cat").css('width', w_child);
					jQuery(this).find('.product_list_by_sub_cat .inner-cms-block').css('width', '100%');
				});
			 }); 
		});
	});
</script> 