<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Rewards
 */
?>
<?php
    $_rewards = $block->getRewards();
    $statistic = $block->getStatistic();
?>
<?php echo $block->getChildHtml('info');?>
<?php if ($_rewards && count($_rewards)) : ?>


    <div class="fieldset-wrapper customer-information">
       
		
		<div class="point-summary">
				<div class="my-points">
				<div class="points-head"><?php /* @escapeNotVerified */ echo __('My points') ?> </div>
				<h2><?php /* @escapeNotVerified */ echo $currentbalance = ($statistic['positiveTotal'] + $statistic['negativeTotal'])?><span class="ptsclass"><?php  echo __('Pts') ?></span></h2>
				</div>
			<div class="my-rewards">
			 <div class="points-head"><?php /* @escapeNotVerified */ echo __('My Rewards') ?> </div>
			  <h2><?php  
						  if($currentbalance <= 150){
							 $required = 150-$currentbalance;
							   echo /* @escapeNotVerified */ $required."<span>pts away</span>"; ?>
							   </h2>
					<div class="relable"><?php echo __('to get &#163; 15.00 voucher rewards') ?></div>
							   <?php
							  }else{ ?> 
							 <div class="fullfill"> <?php echo __('you fill reward condition');?></div> 
							 <?php } ?>
			</div>
			<div class="shop_now reward"><a href="<?php echo $this->getUrl('face.html')?>"><?php echo __('Shop Now') ?></a></div>
        </div>
		
		
	
    </div>
       

	   
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Rewards') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
				 <th scope="col" class="col action"><?php /* @escapeNotVerified */ echo __('Activity') ?></th>
                <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Points') ?></th>
                <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Comment') ?></th>
                
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_rewards as $_reward) : ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date">
					<?php  $date = $block->formatDate($_reward->getActionDate());
                          echo date('d/m/Y',strtotime($date));
					?></td>
					  <td data-th="<?php echo $block->escapeHtml(__('Action')) ?>" class="col status"><?php /* @escapeNotVerified */ echo $_reward->getAction() ?></td>
					  
                    <td data-th="<?php echo $block->escapeHtml(__('Amount')) ?>" class="col amount">
                        <?php /* @escapeNotVerified */ echo $_reward->getAmount() > 0 ? '+'.$_reward->getAmount() : $_reward->getAmount() ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Comment')) ?>" class="col comment"><?php echo $_reward->getComment() ?></td>
                  
                   
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have no rewards.'); ?></span></div>
<?php endif ?>
