<?php
/**
 * Copyright (c) MageWorkshop. All rights reserved.
 * This source file is subject to the MageWorkshop License https://mageworkshop.com/terms-of-service
 * Do not change this file if you want to upgrade the module to the newer versions in the future
 * Please, contact us at https://mageworkshop.com/contact if you wish to customize this module according to you business needs
 */
namespace MageWorkshop\CustomerPermissions\Model\Rewrite\Customer\Model\Indexer;

class Source extends \Magento\Customer\Model\Indexer\Source
{
    /**
     * Add this missed method for fixing indexing if customer EAV attributes are present
     * in our case it's 'banned_till' attribute
     * Need to be removed as soon as the fix https://github.com/magento/magento2/pull/12729/files is merged
     * Please refer to https://github.com/magento/magento2/issues/10838
     *
     * @param string $fieldName
     * @param mixed $alias
     * @return $this
     */
    public function addAttributeToSelect($fieldName, $alias = null)
    {
        return $this->addFieldToSelect($fieldName, $alias);
    }
}
