<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$storeID = $storeManager->getStore()->getStoreId(); 

$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$customerId = $customerSession->getCustomerId();
$registry = $objectManager->create('\Amasty\Rewards\Model\Rewards')->getCustomerRewards($customerId);
#$reward_points = $registry->registry('current_amasty_rewards_statistic');
//echo '<pre>'; print_r($registry->getData());die("tststt");

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$orderCollection = $objectManager->create('\Magento\Sales\Model\ResourceModel\Order\Collection');
$orderCollection->addAttributeToFilter('customer_id',$customerId)
                 ->load();

//echo "<pre>";print_r($orderCollection->getData()); exit;
$ordercount =  count($orderCollection); 
 ?>
<div class="block block-dashboard-info mt-5">


<div class="fieldset-wrapper customer-information">
        
        
        <div class="point-summary">
			<div class="my-points">
				<div class="points-head"><?php /* @escapeNotVerified */ echo __('نقاطي') ?> </div>
				<h2><?php $collection = $registry->getData(); 
				echo $currentbalance = $collection ? $collection[0]['points_left'] : 0;?>
				<span><?php  echo __('نقطة') ?></span></h2>
			</div>
			<div class="my-rewards">
			 <div class="points-head"><?php /* @escapeNotVerified */ echo __('جوائزي') ?> </div>
			  <h2><?php  
						  if($currentbalance <= 500){
							 $required = 500-$currentbalance;
							   echo /* @escapeNotVerified */ "<span>على بعد</span> ".$required."<span>نقطة</span> "; ?>
							   </h2>
						 <!--<div class="relable">-->
						 <!--<?php if($storeID == 11 || $storeID == 12){ ?>-->
       <!--                         <?php echo __('للحصول على قسيمة شرائية بقيمة 15.00 دينار') ?>-->
						 <!--<?php } else { ?>-->
						 <!-- <?php echo __('للحصول على قسيمة شرائية بقيمة 15.00 &#128;') ?>-->
						 <!--<?php } ?>-->
						 <!--</div>-->
							   <?php
							  }?>
							  
							<h2><?php if($currentbalance >= 500){
							 $required = 0;
							   echo /* @escapeNotVerified */ "<span>على بعد</span> ".$required."<span>نقطة</span> "; ?>
							   </h2>
						 <!--<div class="relable">-->
						 <!--<?php if($storeID == 11 || $storeID == 12){ ?>-->
       <!--                         <?php echo __('للحصول على قسيمة شرائية بقيمة 15.00 دينار') ?>-->
						 <!--<?php } else { ?>-->
						 <!-- <?php echo __('للحصول على قسيمة شرائية بقيمة 15.00 &#128;') ?>-->
						 <!--<?php } ?>-->
						 
						 
						 <!--</div>-->
						 <?php } ?>
			</div>
		<div class="shop_now reward"><a href="<?php echo $this->getUrl('face.html')?>"><?php echo __('Shop Now') ?></a></div>
        </div>
        
    </div>
	<?php if($ordercount=="0"){ ?>
	 <table class="data table table-order-items history customordertable">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
            <thead>
                <tr>
				    <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Order Date') ?></th>
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('رقم الطلب') ?></th>
                    <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Items') ?></th>
                    <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Total Paid') ?></th>
                    <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                   
                </tr>
            </thead>
       
        </table>
 <?php }?>
 
</div>
