<?php
/**
 * Copyright (c) MageWorkshop. All rights reserved.
 * This source file is subject to the MageWorkshop License https://mageworkshop.com/terms-of-service
 * Do not change this file if you want to upgrade the module to the newer versions in the future
 * Please, contact us at https://mageworkshop.com/contact if you wish to customize this module according to you business needs
 */
?>
<?php /** @var \Magento\Review\Block\Product\Review $block */ ?>
<div class="detailed-review-wrapper">
    <?= $block->getChildHtml() ?>
    <div id="product-review-container" data-role="product-review"></div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= /* @escapeNotVerified */ $block->getProductReviewUrl() ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }

</script>