<?php
/**
 * Copyright (c) MageWorkshop. All rights reserved.
 * This source file is subject to the MageWorkshop License https://mageworkshop.com/terms-of-service
 * Do not change this file if you want to upgrade the module to the newer versions in the future
 * Please, contact us at https://mageworkshop.com/contact if you wish to customize this module according to you business needs
 */
?>
<?php
    $hideBy = $this->helper(\MageWorkshop\Seo\Helper\Data::class)->getHideStyle();
?>
<?php if ($hideBy === \MageWorkshop\Seo\Model\Config\Source\HideBlockBy::HIDE_BY_JS): ?>
    <script type="text/x-magento-init">
        {
            "#customer-reviews-seo": {
                "MageWorkshop_Seo": {}
            }
        }
    </script>
<?php endif; ?>
<div id="customer-reviews-seo" <?= $hideBy === \MageWorkshop\Seo\Model\Config\Source\HideBlockBy::HIDE_BY_CSS ? 'style="display:none"' : ''; ?>>
    <?= $this->getChildHtml('product_additional_data'); ?>
</div>
